decompiler: TypePointerRel Class Reference
TypePointerRel Class Reference
#include <type.hh>
Public Member Functions
TypePointerRel (const TypePointerRel &op)
Construct from another TypePointerRel.
TypePointerRel (int4 sz, Datatype *pt, uint4 ws, Datatype *par, int4 off)
Construct given a size, pointed-to type, parent, and offset.
bool evaluateThruParent (uintb addrOff) const
Do we display given address offset as coming from the parent data-type.
int4 getPointerOffset (void) const
Get offset of this pointer relative to start of the containing data-type.
virtual void printRaw (ostream &s) const
Print a description of the type to stream.
virtual int4 compareDependency (const Datatype &op) const
Compare for storage in tree structure.
virtual Datatype * clone (void) const
Clone the data-type.
virtual void saveXml (ostream &s) const
Serialize the data-type to XML.
virtual TypePointer * downChain (uintb &off, TypePointer *&par, uintb &parOff, bool allowArrayWrap, TypeFactory &typegrp)
Find a sub-type pointer given an offset into this.
virtual bool isPtrsubMatching (uintb off) const
Is this data-type suitable as input to a CPUI_PTRSUB op.
Public Member Functions inherited from TypePointer
TypePointer (const TypePointer &op)
Construct from another TypePointer.
TypePointer (int4 s, Datatype *pt, uint4 ws)
Construct from a size, pointed-to type, and wordsize.
TypePointer (Datatype *pt, AddrSpace *spc)
Construct from a pointed-to type and an address space attribute.
virtual int4 numDepend (void) const
virtual Datatype * getDepend (int4 index) const
virtual void printNameBase (ostream &s) const
virtual int4 compare (const Datatype &op, int4 level) const
Order types for propagation.
virtual Datatype * resolveInFlow (PcodeOp *op, int4 slot)
Tailor data-type propagation based on Varnode use.
virtual Datatype * findResolve (const PcodeOp *op, int4 slot)
Find a previously resolved sub-type.
Public Member Functions inherited from Datatype
Datatype (const Datatype &op)
Construct the base data-type copying low-level properties of another.
Datatype (int4 s, type_metatype m)
Construct the base data-type providing size and meta-type.
bool hasSameVariableBase (const Datatype *ct) const
Are these the same variable length data-type.
uint4 getDisplayFormat (void) const
Get the display format for constants with this data-type.
virtual Datatype * getSubType (uintb off, uintb *newoff) const
Recover component data-type one-level down.
virtual Datatype * nearestArrayedComponentForward (uintb off, uintb *newoff, int4 *elSize) const
virtual Datatype * nearestArrayedComponentBackward (uintb off, uintb *newoff, int4 *elSize) const
virtual Datatype * getStripped (void) const
Get a stripped version of this for formal use in formal declarations.
virtual int4 findCompatibleResolve (Datatype *ct) const
Find a resolution compatible with the given data-type.
int4 typeOrderBool (const Datatype &op) const
Order this with -op-, treating bool data-type as special.
void saveXmlRef (ostream &s) const
Write an XML reference of this to stream.
Static Public Member Functions
static Datatype * getPtrToFromParent (Datatype *base, int4 off, TypeFactory &typegrp)
Given a containing data-type and offset, find the "pointed to" data-type suitable for a TypePointerRel.
Static Public Member Functions inherited from Datatype
static uint4 encodeIntegerFormat (const string &val)
Encode the format attribute from an XML element.
static string decodeIntegerFormat (uint4 val)
Decode the given format value into an XML attribute string.
Protected Member Functions
void cacheStrippedType (TypeFactory &typegrp)
Set up the base pointer data-type this is modeling.
void restoreXml (const Element *el, TypeFactory &typegrp)
TypePointerRel (void)
Internal constructor for restoreXml.
Protected Member Functions inherited from TypePointer
void restoreXml (const Element *el, TypeFactory &typegrp)
Restore this pointer data-type from an XML element.
void calcSubmeta (void)
Pointers to structures may require a specific submeta.
TypePointer (void)
Internal constructor for use with restoreXml.
Protected Member Functions inherited from Datatype
void restoreXmlBasic (const Element *el)
Recover basic data-type properties.
void saveXmlBasic (type_metatype meta, ostream &s) const
Save basic data-type properties.
void saveXmlTypedef (ostream &s) const
Write this as a typedef tag to stream.
void setDisplayFormat (uint4 format)
Set a specific display format.
Protected Attributes
TypePointer * stripped
Same data-type with container info stripped.
Datatype * parent
Parent structure or array which this is pointing into.
int4 offset
Byte offset within the parent where this points to.
Protected Attributes inherited from TypePointer
Datatype * ptrto
Type being pointed to.
AddrSpace * spaceid
If non-null, the address space this is intented to point into.
uint4 wordsize
What size unit does the pointer address.
Protected Attributes inherited from Datatype
int4 size
Size (of variable holding a value of this type)
string name
Name of type.
type_metatype metatype
Meta-type - type disregarding size.
sub_metatype submeta
Sub-type of of the meta-type, for comparisons.
uint4 flags
Boolean properties of the type.
uint8 id
A unique id for the type (or 0 if an id is not assigned)
Datatype * typedefImm
The immediate data-type being typedefed by this.
Friends
class TypeFactory
Additional Inherited Members
Protected Types inherited from Datatype
enum {
coretype = 1, chartype = 2, enumtype = 4, poweroftwo = 8,
utf16 = 16, utf32 = 32, opaque_string = 64, variable_length = 128,
has_stripped = 0x100, is_ptrrel = 0x200, type_incomplete = 0x400, needs_resolution = 0x800,
force_format = 0x7000
}
Boolean properties of datatypes.
Static Protected Member Functions inherited from Datatype
static uint8 hashName (const string &nm)
Produce a data-type id by hashing the type name.
static uint8 hashSize (uint8 id, int4 size)
Reversibly hash size into id.
Static Protected Attributes inherited from Datatype
static sub_metatype base2sub [14]
Detailed Description
The other data, the container, is typically a TypeStruct or TypeArray. Even though this pointer does not point directly to the start of the container, it is possible to access the container through this, as the distance (the offset) to the start of the container is explicitly known.
Member Function Documentation
cacheStrippedType()
void TypePointerRel::cacheStrippedType (TypeFactory & typegrp) inline protected
Set up the base pointer data-type this is modeling.
This base data-type is used for formal variable declarations in source code output. Calling this method marks the TypePointerRel as an ephemeral data-type. The TypePointerRel is not considered a formal data-type and is replaced with the base pointer data-type, after propagation, in the final decompiler output.
Parameters
typegrp is the factory from which to fetch the base pointer
References Datatype::flags, TypeFactory::getTypePointer(), Datatype::has_stripped, TypePointer::ptrto, Datatype::size, stripped, and TypePointer::wordsize.
Referenced by TypeFactory::getTypePointerRel().
compareDependency()
int4 TypePointerRel::compareDependency (const Datatype & op) const virtual
Compare for storage in tree structure.
Sort data-types for the main TypeFactory container. The sort needs to be based on the data-type structure so that an example data-type, constructed outside the factory, can be used to find the equivalent object inside the factory. This means the comparison should not examine the data-type id. In practice, the comparison only needs to go down one level in the component structure before just comparing component pointers.
Parameters
op is the data-type to compare with this
Returns
negative, 0, positive depending on ordering of types
Reimplemented from TypePointer.
References offset, parent, TypePointer::ptrto, Datatype::size, Datatype::submeta, and TypePointer::wordsize.
downChain()
TypePointer * TypePointerRel::downChain (uintb & off, TypePointer *& par, uintb & parOff, bool allowArrayWrap, TypeFactory & typegrp) virtual
Find a sub-type pointer given an offset into this.
Add a constant offset to this pointer. If there is a valid component at that offset, return a pointer to the data-type of the component or NULL otherwise. This routine only goes down one level at most. Pass back the renormalized offset relative to the new data-type. If this is a pointer to (into) a container, the data-type of the container is passed back, with the offset into the container.
Parameters
off is a reference to the offset to add
par is used to pass back the container
parOff is used to pass back the offset into the container
allowArrayWrap is true if the pointer should be treated as a pointer to an array
typegrp is the factory producing the (possibly new) data-type
Returns
a pointer datatype for the component or NULL
Reimplemented from TypePointer.
References calc_mask(), TypePointer::downChain(), TypeFactory::getTypePointer(), offset, parent, TypePointer::ptrto, Datatype::size, TYPE_ARRAY, TYPE_STRUCT, and TypePointer::wordsize.
evaluateThruParent()
bool TypePointerRel::evaluateThruParent (uintb addrOff) const
Do we display given address offset as coming from the parent data-type.
For a variable that is a relative pointer, constant offsets relative to the variable can be displayed either as coming from the variable itself or from the parent object.
Parameters
addrOff is the given offset in address units
Returns
true if the variable should be displayed as coming from the parent
References AddrSpace::addressToByte(), calc_mask(), offset, TypePointer::ptrto, Datatype::size, TYPE_STRUCT, and TypePointer::wordsize.
Referenced by AddTreeState::calcSubtype().
getPointerOffset()
int4 TypePointerRel::getPointerOffset (void) const inline
Get offset of this pointer relative to start of the containing data-type.
Returns
the offset value in address units
References AddrSpace::byteToAddressInt(), offset, and TypePointer::wordsize.
Referenced by AddTreeState::AddTreeState(), RuleStructOffset0::applyOp(), AddTreeState::calcSubtype(), PrintC::opPtrsub(), and TypeOpEqual::propagateAcrossCompare().
getPtrToFromParent()
Datatype * TypePointerRel::getPtrToFromParent (Datatype * base, int4 off, TypeFactory & typegrp) static
Given a containing data-type and offset, find the "pointed to" data-type suitable for a TypePointerRel.
The biggest contained data-type that starts at the exact offset is returned. If the offset is negative or the is no data-type starting exactly there, an xunknown1 data-type is returned.
Parameters
base is the given container data-type
off is the offset relative to the start of the container
typegrp is the factory owning the data-types
Returns
the "pointed to" data-type
References TypeFactory::getBase(), Datatype::getSubType(), and TYPE_UNKNOWN.
Referenced by IfcPointerSetting::execute().
isPtrsubMatching()
bool TypePointerRel::isPtrsubMatching (uintb off) const virtual
Is this data-type suitable as input to a CPUI_PTRSUB op.
A CPUI_PTRSUB must act on a pointer data-type where the given offset addresses a component. Perform this check.
Parameters
off is the given offset
Returns
true if this is a suitable PTRSUB data-type
Reimplemented from TypePointer.
References AddrSpace::addressToByteInt(), TypePointer::isPtrsubMatching(), offset, stripped, and TypePointer::wordsize.
printRaw()
void TypePointerRel::printRaw (ostream & s) const virtual
Print a description of the type to stream.
Print a raw description of the type to stream. Intended for debugging. Not intended to produce parsable C.
Parameters
s is the output stream
Reimplemented from TypePointer.
References offset, parent, Datatype::printRaw(), and TypePointer::ptrto.
restoreXml()
void TypePointerRel::restoreXml (const Element * el, TypeFactory & typegrp) protected
Restore this relative pointer data-type from an XML element
Parse a <type> tag with children describing the data-type being pointed to and the parent data-type.
Parameters
el is the root XML element
typegrp is the factory owning this data-type
Referenced by TypeFactory::restoreXmlTypeNoRef().
saveXml()
void TypePointerRel::saveXml (ostream & s) const virtual
Serialize the data-type to XML.
Write out a formal description of the data-type as an XML <type> tag. For composite data-types, the description goes down one level, describing the component types only by reference.
Parameters
s is the stream to write to
Reimplemented from TypePointer.
References a_v_i(), offset, parent, TypePointer::ptrto, Datatype::saveXml(), Datatype::saveXmlBasic(), Datatype::saveXmlRef(), TYPE_PTRREL, and TypePointer::wordsize.
The documentation for this class was generated from the following files:
type.hh
type.cc