decompiler: TypeCode Class Reference
TypeCode Class Reference
Datatype object representing executable code.
#include <type.hh>
Public Member Functions
TypeCode (const TypeCode &op)
Construct from another TypeCode.
TypeCode (void)
Construct an incomplete TypeCode.
int4 compareBasic (const TypeCode *op) const
Compare surface characteristics of two TypeCodes.
virtual void printRaw (ostream &s) const
Print a description of the type to stream.
virtual Datatype * getSubType (uintb off, uintb *newoff) const
Recover component data-type one-level down.
virtual int4 compare (const Datatype &op, int4 level) const
Order types for propagation.
virtual int4 compareDependency (const Datatype &op) const
Compare for storage in tree structure.
virtual Datatype * clone (void) const
Clone the data-type.
virtual void saveXml (ostream &s) const
Serialize the data-type to XML.
Public Member Functions inherited from Datatype
Datatype (const Datatype &op)
Construct the base data-type copying low-level properties of another.
Datatype (int4 s, type_metatype m)
Construct the base data-type providing size and meta-type.
bool hasSameVariableBase (const Datatype *ct) const
Are these the same variable length data-type.
uint4 getDisplayFormat (void) const
Get the display format for constants with this data-type.
virtual Datatype * nearestArrayedComponentForward (uintb off, uintb *newoff, int4 *elSize) const
virtual Datatype * nearestArrayedComponentBackward (uintb off, uintb *newoff, int4 *elSize) const
virtual bool isPtrsubMatching (uintb off) const
Is this data-type suitable as input to a CPUI_PTRSUB op.
virtual Datatype * getStripped (void) const
Get a stripped version of this for formal use in formal declarations.
virtual Datatype * resolveInFlow (PcodeOp *op, int4 slot)
Tailor data-type propagation based on Varnode use.
virtual Datatype * findResolve (const PcodeOp *op, int4 slot)
Find a previously resolved sub-type.
virtual int4 findCompatibleResolve (Datatype *ct) const
Find a resolution compatible with the given data-type.
int4 typeOrderBool (const Datatype &op) const
Order this with -op-, treating bool data-type as special.
void saveXmlRef (ostream &s) const
Write an XML reference of this to stream.
Protected Member Functions
void setPrototype (TypeFactory *tfact, ProtoModel *model, Datatype *outtype, const vector< Datatype * > &intypes, bool dotdotdot, Datatype *voidtype)
Establish a function pointer.
void setPrototype (TypeFactory *typegrp, const FuncProto *fp)
Set a particular function prototype on this.
void restoreStub (const Element *el)
Restore stub of data-type without the full prototype.
void restorePrototype (const Element *el, bool isConstructor, bool isDestructor, TypeFactory &typegrp)
Restore any prototype description.
Protected Member Functions inherited from Datatype
void restoreXmlBasic (const Element *el)
Recover basic data-type properties.
void saveXmlBasic (type_metatype meta, ostream &s) const
Save basic data-type properties.
void saveXmlTypedef (ostream &s) const
Write this as a typedef tag to stream.
void setDisplayFormat (uint4 format)
Set a specific display format.
Protected Attributes
FuncProto * proto
If non-null, this describes the prototype of the underlying function.
TypeFactory * factory
Factory owning this.
Protected Attributes inherited from Datatype
int4 size
Size (of variable holding a value of this type)
string name
Name of type.
type_metatype metatype
Meta-type - type disregarding size.
sub_metatype submeta
Sub-type of of the meta-type, for comparisons.
uint4 flags
Boolean properties of the type.
uint8 id
A unique id for the type (or 0 if an id is not assigned)
Datatype * typedefImm
The immediate data-type being typedefed by this.
Friends
class TypeFactory
Additional Inherited Members
Static Public Member Functions inherited from Datatype
static uint4 encodeIntegerFormat (const string &val)
Encode the format attribute from an XML element.
static string decodeIntegerFormat (uint4 val)
Decode the given format value into an XML attribute string.
Protected Types inherited from Datatype
enum {
coretype = 1, chartype = 2, enumtype = 4, poweroftwo = 8,
utf16 = 16, utf32 = 32, opaque_string = 64, variable_length = 128,
has_stripped = 0x100, is_ptrrel = 0x200, type_incomplete = 0x400, needs_resolution = 0x800,
force_format = 0x7000
}
Boolean properties of datatypes.
Static Protected Member Functions inherited from Datatype
static uint8 hashName (const string &nm)
Produce a data-type id by hashing the type name.
static uint8 hashSize (uint8 id, int4 size)
Reversibly hash size into id.
Static Protected Attributes inherited from Datatype
static sub_metatype base2sub [14]
Detailed Description
Datatype object representing executable code.
Sometimes, this holds the "function" being pointed to by a function pointer
Member Function Documentation
compare()
int4 TypeCode::compare (const Datatype & op, int4 level) const virtual
Order types for propagation.
Order this with another data-type, in a way suitable for the type propagation algorithm. Bigger types come earlier. More specific types come earlier.
Parameters
op is the data-type to compare with this
level is maximum level to descend when recursively comparing
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References Datatype::compare(), compareBasic(), and proto.
compareBasic()
int4 TypeCode::compareBasic (const TypeCode * op) const
Compare surface characteristics of two TypeCodes.
Compare basic characteristics of this with another TypeCode, not including the prototype
-1 or 1 if -this- and -op- are different in surface characteristics
0 if they are exactly equal and have no parameters
2 if they are equal on the surface, but additional comparisons must be made on parameters
Parameters
op is the other data-type to compare to
Returns
the comparison value
References FuncProto::getComparableFlags(), and proto.
Referenced by compare(), and compareDependency().
compareDependency()
int4 TypeCode::compareDependency (const Datatype & op) const virtual
Compare for storage in tree structure.
Sort data-types for the main TypeFactory container. The sort needs to be based on the data-type structure so that an example data-type, constructed outside the factory, can be used to find the equivalent object inside the factory. This means the comparison should not examine the data-type id. In practice, the comparison only needs to go down one level in the component structure before just comparing component pointers.
Parameters
op is the data-type to compare with this
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References compareBasic(), Datatype::compareDependency(), and proto.
getSubType()
Datatype * TypeCode::getSubType (uintb off, uintb * newoff) const virtual
Recover component data-type one-level down.
Given an offset into this data-type, return the component data-type at that offset. Also, pass back a "renormalized" offset suitable for recursize getSubType() calls: i.e. if the original offset hits the exact start of the sub-type, 0 is passed back. If there is no valid component data-type at the offset, return NULL and pass back the original offset
Parameters
off is the offset into this data-type
newoff is a pointer to the passed-back offset
Returns
a pointer to the component data-type or NULL
Reimplemented from Datatype.
References factory, TypeFactory::getBase(), and TYPE_CODE.
printRaw()
void TypeCode::printRaw (ostream & s) const virtual
Print a description of the type to stream.
Print a raw description of the type to stream. Intended for debugging. Not intended to produce parsable C.
Parameters
s is the output stream
Reimplemented from Datatype.
References Datatype::name.
restorePrototype()
void TypeCode::restorePrototype (const Element * el, bool isConstructor, bool isDestructor, TypeFactory & typegrp) protected
Restore any prototype description.
A single child element indicates a full function prototype.
Parameters
el is the root XML tag describing the code object
isConstructor is true if the prototype is a constructor
isDestructor is true if the prototype is a destructor
typegrp is the factory owning the code object
References Architecture::defaultfp, factory, TypeFactory::getTypeVoid(), proto, FuncProto::restoreXml(), FuncProto::setConstructor(), FuncProto::setDestructor(), and FuncProto::setInternal().
Referenced by TypeFactory::restoreCode().
restoreStub()
void TypeCode::restoreStub (const Element * el) protected
Restore stub of data-type without the full prototype.
Parameters
el is the root XML element describing the code object
References Datatype::flags, Datatype::restoreXmlBasic(), and Datatype::variable_length.
Referenced by TypeFactory::restoreCode().
saveXml()
void TypeCode::saveXml (ostream & s) const virtual
Serialize the data-type to XML.
Write out a formal description of the data-type as an XML <type> tag. For composite data-types, the description goes down one level, describing the component types only by reference.
Parameters
s is the stream to write to
Reimplemented from Datatype.
References Datatype::metatype, proto, FuncProto::saveXml(), Datatype::saveXmlBasic(), Datatype::saveXmlTypedef(), and Datatype::typedefImm.
setPrototype() [1/2]
void TypeCode::setPrototype (TypeFactory * tfact, ProtoModel * model, Datatype * outtype, const vector< Datatype * > & intypes, bool dotdotdot, Datatype * voidtype) protected
Establish a function pointer.
Turn on the data-type's function prototype
Parameters
tfact is the factory that owns this
model is the prototype model
outtype is the return type of the prototype
intypes is the list of input parameters
dotdotdot is true if the prototype takes variable arguments
voidtype is the reference "void" data-type
References factory, Datatype::flags, proto, FuncProto::setInputLock(), FuncProto::setInternal(), FuncProto::setOutputLock(), FuncProto::updateAllTypes(), and Datatype::variable_length.
Referenced by TypeFactory::getTypeCode(), and TypeFactory::setPrototype().
setPrototype() [2/2]
void TypeCode::setPrototype (TypeFactory * typegrp, const FuncProto * fp) protected
Set a particular function prototype on this.
The prototype is copied in.
Parameters
typegrp is the factory owning this
fp is the prototype to set (may be null)
References FuncProto::copy(), factory, and proto.
The documentation for this class was generated from the following files:
type.hh
type.cc