decompiler: RulePtrArith Class Reference
RulePtrArith Class Reference
Transform pointer arithmetic.
Public Member Functions
virtual Rule * clone (const ActionGroupList &grouplist) const
Clone the Rule.
virtual void getOpList (vector< uint4 > &oplist) const
List of op codes this rule operates on.
virtual int4 applyOp (PcodeOp *op, Funcdata &data)
Attempt to apply this Rule.
Public Member Functions inherited from Rule
Rule (const string &g, uint4 fl, const string &nm)
Construct given group, properties name.
bool checkActionBreak (void)
Check if an action breakpoint is turned on.
virtual void reset (Funcdata &data)
Reset this Rule.
virtual void resetStats (void)
Reset Rule statistics.
virtual void printStatistics (ostream &s) const
Print statistics for this Rule.
Static Public Member Functions
static int4 evaluatePointerExpression (PcodeOp *op, int4 slot)
Determine if the expression rooted at the given INT_ADD operation is ready for conversion.
Static Private Member Functions
static bool verifyPreferredPointer (PcodeOp *op, int4 slot)
Test for other pointers in the ADD tree above the given op that might be a preferred base.
Additional Inherited Members
Public Types inherited from Rule
enum typeflags { type_disable = 1, rule_debug = 2, warnings_on = 4, warnings_given = 8 }
Properties associated with a Rule.
Detailed Description
Transform pointer arithmetic.
Rule for converting integer arithmetic to pointer arithmetic. A string of INT_ADDs is converted into PTRADDs and PTRSUBs.
Basic algorithm: Starting with a varnode of known pointer type (with known size):
Generate list of terms added to pointer
Find all terms that are multiples of pointer size
Find all terms that are smaller than pointer size
Find sum of constants smaller than pointer size
Multiples get converted to PTRADD
Constant gets converted to nearest subfield offset
Everything else is just added back on
We need to be wary of most things being in the units of the space being pointed at. Type calculations are always in bytes so we need to convert between space units and bytes.
Member Function Documentation
applyOp()
int4 RulePtrArith::applyOp (PcodeOp * op, Funcdata & data) virtual
Attempt to apply this Rule.
This method contains the main logic for applying the Rule. It must use a given PcodeOp as the point at which the Rule applies. If it does apply, changes are made directly to the function and 1 (non-zero) is returned, otherwise 0 is returned.
Parameters
op is the given PcodeOp where the Rule may apply
data is the function to which to apply
Reimplemented from Rule.
References AddTreeState::apply(), evaluatePointerExpression(), AddTreeState::initAlternateForm(), TYPE_PTR, and verifyPreferredPointer().
clone()
virtual Rule* RulePtrArith::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Rule.
If this Rule is a member of one of the groups in the grouplist, this returns a clone of the Rule, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Rule or NULL
Implements Rule.
References ActionGroupList::contains().
evaluatePointerExpression()
int4 RulePtrArith::evaluatePointerExpression (PcodeOp * op, int4 slot) static
Determine if the expression rooted at the given INT_ADD operation is ready for conversion.
Converting an expression of INT_ADDs into PTRSUBs and PTRADDs requires that the base pointer be at the root of the expression tree. This method evaluates whether given root has the base pointer at the bottom. If not, a push transform needs to be performed before RulePtrArith can apply. This method returns a command code:
0 if no action should be taken, the expression is not fully linked or should not be converted
1 if a push action should be taken, prior to conversion
2 if the pointer arithmetic conversion can proceed
Parameters
op is the given INT_ADD
slot is the index of the pointer
Returns
the command code
References CPUI_INT_ADD, CPUI_LOAD, CPUI_STORE, PcodeOp::getSlot(), Varnode::getTypeReadFacing(), and TYPE_PTR.
Referenced by applyOp(), RulePushPtr::applyOp(), and verifyPreferredPointer().
getOpList()
void RulePtrArith::getOpList (vector< uint4 > & oplist) const virtual
List of op codes this rule operates on.
Populate the given array with all possible OpCodes this Rule might apply to. By default, this method returns all possible OpCodes
Parameters
oplist is the array to populate
Reimplemented from Rule.
References CPUI_INT_ADD.
verifyPreferredPointer()
bool RulePtrArith::verifyPreferredPointer (PcodeOp * op, int4 slot) static private
Test for other pointers in the ADD tree above the given op that might be a preferred base.
This tests the condition of RulePushPtr on the node immediately above the given putative base pointer
Parameters
op is the given op
slot is the input slot of the putative base pointer
Returns
true if the indicated slot holds the preferred pointer
References CPUI_INT_ADD, evaluatePointerExpression(), and TYPE_PTR.
Referenced by applyOp().
The documentation for this class was generated from the following files:
ruleaction.hh
ruleaction.cc