decompiler: ParamListStandard Class Reference
ParamListStandard Class Reference
A standard model for parameters as an ordered list of storage resources.
#include <fspec.hh>
Public Member Functions
ParamListStandard (const ParamListStandard &op2)
Copy constructor.
virtual uint4 getType (void) const
Get the type of parameter list.
virtual void assignMap (const vector< Datatype * > &proto, TypeFactory &typefactory, vector< ParameterPieces > &res) const
Given list of data-types, map the list positions to storage locations.
virtual void fillinMap (ParamActive *active) const
Given an unordered list of storage locations, calculate a function prototype.
virtual bool checkJoin (const Address &hiaddr, int4 hisize, const Address &loaddr, int4 losize) const
Check if the given two storage locations can represent a single logical parameter.
virtual bool checkSplit (const Address &loc, int4 size, int4 splitpoint) const
Check if it makes sense to split a single storage location into two parameters.
virtual int4 characterizeAsParam (const Address &loc, int4 size) const
Characterize whether the given range overlaps parameter storage.
virtual bool possibleParam (const Address &loc, int4 size) const
Does the given storage location make sense as a parameter.
virtual bool possibleParamWithSlot (const Address &loc, int4 size, int4 &slot, int4 &slotsize) const
Pass-back the slot and slot size for the given storage location as a parameter.
virtual bool getBiggestContainedParam (const Address &loc, int4 size, VarnodeData &res) const
Pass-back the biggest parameter contained within the given range.
virtual bool unjustifiedContainer (const Address &loc, int4 size, VarnodeData &res) const
Check if the given storage location looks like an unjustified parameter.
virtual OpCode assumedExtension (const Address &addr, int4 size, VarnodeData &res) const
Get the type of extension and containing parameter for the given storage.
virtual AddrSpace * getSpacebase (void) const
Get the address space associated with any stack based parameters in this list.
virtual void getRangeList (AddrSpace *spc, RangeList &res) const
For a given address space, collect all the parameter locations within that space.
virtual int4 getMaxDelay (void) const
Return the maximum heritage delay across all possible parameters.
virtual void restoreXml (const Element *el, const AddrSpaceManager *manage, vector< EffectRecord > &effectlist, bool normalstack)
Restore the model from an XML stream.
virtual ParamList * clone (void) const
Clone this parameter list model.
Protected Member Functions
const ParamEntry * findEntry (const Address &loc, int4 size) const
Given storage location find matching ParamEntry.
Address assignAddress (const Datatype *tp, vector< int4 > &status) const
Assign storage for given parameter data-type.
const ParamEntry * selectUnreferenceEntry (int4 grp, type_metatype prefType) const
Select entry to fill an unreferenced param.
void buildTrialMap (ParamActive *active) const
Build map from parameter trials to model ParamEntrys.
void separateSections (ParamActive *active, int4 &oneStart, int4 &oneStop, int4 &twoStart, int4 &twoStop) const
Calculate the range of trials in each of the two resource sections.
void calcDelay (void)
Calculate the maximum heritage delay for any potential parameter in this list.
void addResolverRange (AddrSpace *spc, uintb first, uintb last, ParamEntry *paramEntry, int4 position)
Internal method for adding a single address range to the ParamEntryResolvers.
void populateResolver (void)
Build the ParamEntry resolver maps.
void parsePentry (const Element *el, const AddrSpaceManager *manage, vector< EffectRecord > &effectlist, int4 groupid, bool normalstack, bool autokill, bool splitFloat, bool grouped)
Read a <pentry> tag and add it to this list.
void parseGroup (const Element *el, const AddrSpaceManager *manage, vector< EffectRecord > &effectlist, int4 groupid, bool normalstack, bool autokill, bool splitFloat)
Read a group of <pentry> tags that are allocated as a group.
Static Protected Member Functions
static void markGroupNoUse (ParamActive *active, int4 groupUpper, int4 groupStart, int4 index)
Mark all the trials within the indicated groups as not used, except for one specified index.
static void markBestInactive (ParamActive *active, int4 group, int4 groupStart, type_metatype prefType)
From among multiple inactive trials, select the most likely to be active and mark others as not used.
static void forceExclusionGroup (ParamActive *active)
Enforce exclusion rules for the given set of parameter trials.
static void forceNoUse (ParamActive *active, int4 start, int4 stop)
Mark every trial above the first "definitely not used" as inactive.
static void forceInactiveChain (ParamActive *active, int4 maxchain, int4 start, int4 stop, int4 groupstart)
Enforce rules about chains of inactive slots.
Protected Attributes
int4 numgroup
Number of groups in this parameter convention.
int4 maxdelay
Maximum heritage delay across all parameters.
int4 pointermax
If non-zero, maximum size of a data-type before converting to a pointer.
bool thisbeforeret
Does a this parameter come before a hidden return parameter.
int4 resourceTwoStart
If there are two resource sections, the group of the first entry in the second section.
list< ParamEntry > entry
The ordered list of parameter entries.
vector< ParamEntryResolver * > resolverMap
Map from space id to resolver.
AddrSpace * spacebase
Address space containing relative offset parameters.
Additional Inherited Members
Public Types inherited from ParamList
enum {
p_standard, p_standard_out, p_register, p_register_out,
p_merged
}
Detailed Description
A standard model for parameters as an ordered list of storage resources.
This is a configurable model for passing (input) parameters as a list to a function. The model allows 1 or more resource lists based on data-type, either TYPE_UNKNOWN for general purpose or TYPE_FLOAT for floating-point registers. Within a resource list, any number of parameters can be used but they must come starting at the beginning of the list with no holes (skipped resources). A resource list can include (at the end) stack parameters that are allocated based on an alignment. Optionally, the model supports converting data-types larger than a specified size to pointers within the parameter list.
Member Function Documentation
addResolverRange()
void ParamListStandard::addResolverRange (AddrSpace * spc, uintb first, uintb last, ParamEntry * paramEntry, int4 position) protected
Internal method for adding a single address range to the ParamEntryResolvers.
Specify the contiguous address range, the ParamEntry to map to it, and a position recording the order in which ranges are added.
Parameters
spc is address space of the memory range
first is the starting offset of the memory range
last is the ending offset of the memory range
paramEntry is the ParamEntry to associate with the memory range
position is the ordering position
References AddrSpace::getIndex(), rangemap< _recordtype >::insert(), and resolverMap.
Referenced by populateResolver().
assignAddress()
Address ParamListStandard::assignAddress (const Datatype * tp, vector< int4 > & status) const protected
Assign storage for given parameter data-type.
Given the next data-type and the status of previously allocated slots, select the storage location for the parameter. The status array is indexed by group: a positive value indicates how many slots have been allocated from that group, and a -1 indicates the group/resource is fully consumed.
Parameters
tp is the data-type of the next parameter
status is an array marking how many slots have already been consumed in a group
Returns
the newly assigned address for the parameter
References entry, ParamEntry::getAddrBySlot(), Address::isInvalid(), and TYPE_UNKNOWN.
Referenced by assignMap(), ParamListRegisterOut::assignMap(), and ParamListStandardOut::assignMap().
assignMap()
void ParamListStandard::assignMap (const vector< Datatype * > & proto, TypeFactory & typefactory, vector< ParameterPieces > & res) const virtual
Given list of data-types, map the list positions to storage locations.
If we know the function prototype, recover how parameters are actually stored using the model.
Parameters
proto is the ordered list of data-types
typefactory is the TypeFactory (for constructing pointers)
res will contain the storage locations corresponding to the datatypes
Implements ParamList.
Reimplemented in ParamListMerged, ParamListStandardOut, and ParamListRegisterOut.
References assignAddress(), AddrSpace::getAddrSize(), TypeFactory::getTypePointer(), AddrSpace::getWordSize(), ParameterPieces::hiddenretparm, ParameterPieces::indirectstorage, numgroup, pointermax, and spacebase.
assumedExtension()
OpCode ParamListStandard::assumedExtension (const Address & addr, int4 size, VarnodeData & res) const virtual
Get the type of extension and containing parameter for the given storage.
If the given storage is properly contained within a normal parameter and the model typically extends a small value into the full container, pass back the full container and the type of extension.
Parameters
addr is the starting address of the given storage
size is the number of bytes in the given storage
res is the parameter storage to pass back
Returns
the extension operator (INT_ZEXT INT_SEXT) or INT_COPY if there is no extension. INT_PIECE indicates the extension is determined by the specific prototype.
Implements ParamList.
References CPUI_COPY, and entry.
buildTrialMap()
void ParamListStandard::buildTrialMap (ParamActive * active) const protected
Build map from parameter trials to model ParamEntrys.
Given a set of trials (putative Varnode parameters) as ParamTrial objects, associate each trial with a model ParamEntry within this list. Trials for for which there are no matching entries are marked as unused. Any holes in the resource list are filled with unreferenced trials. The trial list is sorted.
Parameters
active is the set of trials to map and organize
References findEntry(), ParamEntry::getAddrBySlot(), ParamEntry::getSlot(), ParamActive::registerTrial(), selectUnreferenceEntry(), TYPE_FLOAT, and TYPE_UNKNOWN.
Referenced by fillinMap().
characterizeAsParam()
int4 ParamListStandard::characterizeAsParam (const Address & loc, int4 size) const virtual
Characterize whether the given range overlaps parameter storage.
Does the range naturally fit inside a potential parameter entry from this list or does it contain a parameter entry. Return one of four enumerations indicating this characterization:
no_containment - there is no containment between the range and any parameter in this list
contains_unjustified - at least one parameter contains the range
contains_justified - at least one parameter contains this range as its least significant bytes
contained_by - no parameter contains this range, but the range contains at least one parameter
Parameters
loc is the starting address of the given range
size is the number of bytes in the given range
Returns
the characterization code
Implements ParamList.
References ParamEntry::contained_by, ParamEntry::containedBy(), ParamEntry::contains_justified, ParamEntry::contains_unjustified, rangemap< _recordtype >::find(), rangemap< _recordtype >::find_end(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), ParamEntry::justifiedContain(), ParamEntry::no_containment, and resolverMap.
checkJoin()
bool ParamListStandard::checkJoin (const Address & hiaddr, int4 hisize, const Address & loaddr, int4 losize) const virtual
Check if the given two storage locations can represent a single logical parameter.
Within the conventions of this model, do the two (hi/lo) locations represent consecutive parameter locations that can be replaced by a single logical parameter.
Parameters
hiaddr is the address of the most significant part of the value
hisize is the size of the most significant part in bytes
loaddr is the address of the least significant part of the value
losize is the size of the least significant part in bytes
Returns
true if the two pieces can be joined
Implements ParamList.
References entry, findEntry(), Address::getOffset(), and Address::isContiguous().
checkSplit()
bool ParamListStandard::checkSplit (const Address & loc, int4 size, int4 splitpoint) const virtual
Check if it makes sense to split a single storage location into two parameters.
A storage location and split point is provided, implying two new storage locations. Does this model allow these locations to be considered parameters.
Parameters
loc is the starting address of provided storage location
size is the size of the location in bytes
splitpoint is the number of bytes to consider in the first (in address order) piece
Returns
true if the storage location can be split
Implements ParamList.
References findEntry().
fillinMap()
void ParamListStandard::fillinMap (ParamActive * active) const virtual
Given an unordered list of storage locations, calculate a function prototype.
A list of input (or output) trials is given, which may have holes, invalid inputs etc. Decide on the formal ordered parameter list. Trials within the ParamActive are added, removed, or reordered as needed.
Parameters
active is the given list of trials
Implements ParamList.
Reimplemented in ParamListMerged, ParamListRegister, and ParamListRegisterOut.
References buildTrialMap(), forceExclusionGroup(), forceInactiveChain(), forceNoUse(), resourceTwoStart, and separateSections().
findEntry()
const ParamEntry * ParamListStandard::findEntry (const Address & loc, int4 size) const protected
Given storage location find matching ParamEntry.
Find the (first) entry containing the given memory range
Parameters
loc is the starting address of the range
size is the number of bytes in the range
Returns
the pointer to the matching ParamEntry or null if no match exists
References rangemap< _recordtype >::find(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), ParamEntry::justifiedContain(), and resolverMap.
Referenced by buildTrialMap(), checkJoin(), checkSplit(), ParamListRegister::fillinMap(), possibleParam(), and possibleParamWithSlot().
forceExclusionGroup()
void ParamListStandard::forceExclusionGroup (ParamActive * active) static protected
Enforce exclusion rules for the given set of parameter trials.
If there are more than one active trials in a single group, and if that group is an exclusion group, mark all but the first trial to defnouse.
Parameters
active is the set of trials
References markBestInactive(), markGroupNoUse(), and TYPE_UNKNOWN.
Referenced by fillinMap().
forceInactiveChain()
void ParamListStandard::forceInactiveChain (ParamActive * active, int4 maxchain, int4 start, int4 stop, int4 groupstart) static protected
Enforce rules about chains of inactive slots.
If there is a chain of slots whose length is greater than maxchain, where all trials are inactive, mark trials in any later slot as inactive. Mark any inactive trials before this (that aren't in a maximal chain) as active. The parameter entries in the model may be split up into different resource sections, as in floating-point vs general purpose. This method must be called on a single section at a time. The start and stop indices describe the range of trials in the particular section.
Parameters
active is the set of trials, which must be sorted
maxchain is the maximum number of inactive trials to allow in a chain
start is the first index in the range of trials to consider
stop is the last index (+1) in the range of trials to consider
groupstart is the smallest group id in the particular section
References IPTR_SPACEBASE.
Referenced by fillinMap().
forceNoUse()
void ParamListStandard::forceNoUse (ParamActive * active, int4 start, int4 stop) static protected
Mark every trial above the first "definitely not used" as inactive.
Inspection and marking only occurs within an indicated range of trials, allowing floating-point and general purpose resources to be treated separately.
Parameters
active is the set of trials, which must already be ordered
start is the index of the first trial in the range to consider
stop is the index (+1) of the last trial in the range to consider
Referenced by fillinMap().
getBiggestContainedParam()
bool ParamListStandard::getBiggestContainedParam (const Address & loc, int4 size, VarnodeData & res) const virtual
Pass-back the biggest parameter contained within the given range.
Parameters
loc is the starting address of the given range
size is the number of bytes in the range
res will hold the parameter storage description being passed back
Returns
true if there is at least one parameter contained in the range
Implements ParamList.
References ParamEntry::containedBy(), rangemap< _recordtype >::find_begin(), rangemap< _recordtype >::find_end(), AddrSpace::getIndex(), Address::getOffset(), Address::getSpace(), VarnodeData::offset, resolverMap, VarnodeData::size, and VarnodeData::space.
getMaxDelay()
virtual int4 ParamListStandard::getMaxDelay (void) const inline virtual
Return the maximum heritage delay across all possible parameters.
Depending on the address space, data-flow for a parameter may not be available until extra transform passes have completed. This method returns the number of passes that must occur before we can guarantee that all parameters have data-flow info.
Returns
the maximum number of passes across all parameters in this model
Implements ParamList.
References maxdelay.
getRangeList()
void ParamListStandard::getRangeList (AddrSpace * spc, RangeList & res) const virtual
For a given address space, collect all the parameter locations within that space.
Pass back the memory ranges for any parameter that is stored in the given address space.
Parameters
spc is the given address space
res will hold the set of matching memory ranges
Implements ParamList.
References entry, and RangeList::insertRange().
getSpacebase()
virtual AddrSpace* ParamListStandard::getSpacebase (void) const inline virtual
Get the address space associated with any stack based parameters in this list.
Returns
the stack address space, if this models parameters passed on the stack, NULL otherwise
Implements ParamList.
References spacebase.
Referenced by ParamListMerged::foldIn().
markBestInactive()
void ParamListStandard::markBestInactive (ParamActive * active, int4 group, int4 groupStart, type_metatype prefType) static protected
From among multiple inactive trials, select the most likely to be active and mark others as not used.
There can be at most one inactive trial in an exclusion group for the fill algorithms to work. Score all the trials and pick the one that is the most likely to actually be an active param. Mark all the others as definitely not used.
Parameters
active is the sorted set of trials
group is the group number
groupStart is the index of the first trial in the group
prefType is a preferred entry to type to use in scoring
References entry, and markGroupNoUse().
Referenced by forceExclusionGroup().
markGroupNoUse()
void ParamListStandard::markGroupNoUse (ParamActive * active, int4 groupUpper, int4 groupStart, int4 index) static protected
Mark all the trials within the indicated groups as not used, except for one specified index.
Only one trial within an exclusion group can have active use, mark all others as unused.
Parameters
active is the set of trials, which must be sorted on group
groupUper is the biggest group number to be marked
groupStart is the index of the first trial in the smallest group to be marked
index is the specified trial index that is not to be marked
Referenced by forceExclusionGroup(), and markBestInactive().
parseGroup()
void ParamListStandard::parseGroup (const Element * el, const AddrSpaceManager * manage, vector< EffectRecord > & effectlist, int4 groupid, bool normalstack, bool autokill, bool splitFloat) protected
Read a group of <pentry> tags that are allocated as a group.
All ParamEntry objects will share the same group id.
Parameters
el is the <pentry element
manage is manager for parsing address spaces
effectlist holds any passed back effect records
groupid is the group to which all ParamEntry elements are assigned
normalstack is true if the parameters should be allocated from the front of the range
autokill is true if parameters are automatically added to the killedbycall list
splitFloat is true if floating-point parameters are in their own resource section
References entry, IPTR_JOIN, numgroup, ParamEntry::orderWithinGroup(), and parsePentry().
Referenced by restoreXml().
parsePentry()
void ParamListStandard::parsePentry (const Element * el, const AddrSpaceManager * manage, vector< EffectRecord > & effectlist, int4 groupid, bool normalstack, bool autokill, bool splitFloat, bool grouped) protected
Read a <pentry> tag and add it to this list.
Parameters
el is the <pentry element
manage is manager for parsing address spaces
effectlist holds any passed back effect records
groupid is the group to which the new ParamEntry is assigned
normalstack is true if the parameters should be allocated from the front of the range
autokill is true if parameters are automatically added to the killedbycall list
splitFloat is true if floating-point parameters are in their own resource section
grouped is true if the new ParamEntry is grouped with other entries
References entry, AddrSpace::getType(), IPTR_SPACEBASE, EffectRecord::killedbycall, numgroup, resourceTwoStart, spacebase, and TYPE_FLOAT.
Referenced by parseGroup(), and restoreXml().
populateResolver()
void ParamListStandard::populateResolver (void) protected
Build the ParamEntry resolver maps.
Enter all the ParamEntry objects into an interval map (based on address space)
References addResolverRange(), entry, AddrSpace::getType(), IPTR_JOIN, VarnodeData::offset, VarnodeData::size, and VarnodeData::space.
Referenced by ParamListStandard(), and restoreXml().
possibleParam()
bool ParamListStandard::possibleParam (const Address & loc, int4 size) const virtual
Does the given storage location make sense as a parameter.
Within this model, decide if the storage location can be considered a parameter.
Parameters
loc is the starting address of the storage location
size is the number of bytes in the storage location
Returns
true if the location can be a parameter
Implements ParamList.
Reimplemented in ParamListRegisterOut.
References findEntry().
possibleParamWithSlot()
bool ParamListStandard::possibleParamWithSlot (const Address & loc, int4 size, int4 & slot, int4 & slotsize) const virtual
Pass-back the slot and slot size for the given storage location as a parameter.
This checks if the given storage location acts as a parameter in this model and passes back the number of slots that it occupies.
Parameters
loc is the starting address of the storage location
size is the number of bytes in the storage location
slot if the slot number to pass back
slotsize is the number of consumed slots to pass back
Returns
true if the location can be a parameter
Implements ParamList.
References findEntry(), and ParamEntry::getSlot().
restoreXml()
void ParamListStandard::restoreXml (const Element * el, const AddrSpaceManager * manage, vector< EffectRecord > & effectlist, bool normalstack) virtual
Restore the model from an XML stream.
Parameters
el is the root <input> or <output> element
manage is used to resolve references to address spaces
effectlist is a container collecting EffectRecords across all parameters
normalstack is true if parameters are pushed on the stack in the normal order
Implements ParamList.
Reimplemented in ParamListStandardOut.
References calcDelay(), Element::getAttributeValue(), numgroup, parseGroup(), parsePentry(), pointermax, populateResolver(), resourceTwoStart, spacebase, thisbeforeret, and xml_readbool().
Referenced by ParamListStandardOut::restoreXml().
selectUnreferenceEntry()
const ParamEntry * ParamListStandard::selectUnreferenceEntry (int4 grp, type_metatype prefType) const protected
Select entry to fill an unreferenced param.
From among the ParamEntrys matching the given group, return the one that best matches the given metatype attribute. If there are no ParamEntrys in the group, null is returned.
Parameters
grp is the given group number
prefType is the preferred metatype attribute to match
References entry, and TYPE_UNKNOWN.
Referenced by buildTrialMap().
separateSections()
void ParamListStandard::separateSections (ParamActive * active, int4 & oneStart, int4 & oneStop, int4 & twoStart, int4 & twoStop) const protected
Calculate the range of trials in each of the two resource sections.
The trials must already be mapped, which should put them in group order. The sections split at the group given by resourceTwoStart. We pass back the range of trial indices for each section. If resourceTwoStart is 0, then there is really only one section, and the empty range [0,0] is passed back for the second section.
Parameters
active is the given set of parameter trials
oneStart will pass back the index of the first trial in the first section
oneStop will pass back the index (+1) of the last trial in the first section
twoStart will pass back the index of the first trial in the second section
twoStop will pass back the index (+1) of the last trial in the second section
References resourceTwoStart.
Referenced by fillinMap().
unjustifiedContainer()
bool ParamListStandard::unjustifiedContainer (const Address & loc, int4 size, VarnodeData & res) const virtual
Check if the given storage location looks like an unjustified parameter.
The storage for a value may be contained in a normal parameter location but be unjustified within that container, i.e. the least significant bytes are not being used. If this is the case, pass back the full parameter location and return true.
Parameters
loc is the starting address of the given storage
size is the number of bytes in the given storage
res is the full parameter storage to pass back
Returns
true if the given storage is unjustified within its parameter container
Implements ParamList.
References entry.
The documentation for this class was generated from the following files:
fspec.hh
fspec.cc