decompiler: IfaceCommand Class Reference
IfaceCommand Class Reference abstract
A command that can be executed from the command line.
#include <interface.hh>
Public Member Functions
virtual void setData (IfaceStatus *root, IfaceData *data)=0
Associate a specific data object with this command.
virtual void execute (istream &s)=0
virtual string getModule (void) const =0
Get the formal module name to which this command belongs.
virtual IfaceData * createData (void)=0
Create a specialized data object for this command (and its module)
void addWord (const string &temp)
Add a token to the command line string associated with this command.
void addWords (const vector< string > &wordlist)
Add words to the associated command line string.
void commandString (string &res) const
Get the complete command line string.
int4 compare (const IfaceCommand &op2) const
Order two commands by their command line strings.
Private Attributes
vector< string > com
The token sequence associated with the command.
Detailed Description
A command that can be executed from the command line.
The command has data associated with it (via setData()) and is executed via the execute() method. The command can get additional parameters from the command line by reading the input stream passed to it. The command is associated with a specific sequence of words (tokens) that should appear at the start of the command line.
Member Function Documentation
addWord()
void IfaceCommand::addWord (const string & temp) inline
Add a token to the command line string associated with this command.
Parameters
temp is the new token to add
Referenced by IfaceStatus::registerCom(), and IfaceStatus::restrictCom().
commandString()
void IfaceCommand::commandString (string & res) const
Get the complete command line string.
Parameters
res is overwritten with the full command line string
References com, and IfaceStatus::wordsToString().
compare()
int4 IfaceCommand::compare (const IfaceCommand & op2) const
Order two commands by their command line strings.
The commands are ordered lexicographically and alphabetically by the comparing tokens in their respective command line strings
Parameters
op2 is the other command to compare with this
Returns
-1, 0, 1 if this is earlier, equal to, or after to the other command
References com.
Referenced by compare_ifacecommand().
createData()
virtual IfaceData* IfaceCommand::createData (void) pure virtual
Create a specialized data object for this command (and its module)
This method is only called once per module
Returns
the newly created data object for the module
Implemented in IfaceBaseCommand, IfaceCommandDummy, and IfaceDecompCommand.
Referenced by IfaceStatus::registerCom().
execute()
virtual void IfaceCommand::execute (istream & s) pure virtual
Execute this command. Additional state can be read from the given command line stream. Otherwise, the command gets its data from its registered IfaceData object
Parameters
s is the input stream from the command line
Implemented in IfcExecuteTestCommand, IfcListTestCommands, IfcLoadTestFile, IfcAnalyzeRange, IfcStructureBlocks, IfcPreferSplit, IfcPointerSetting, IfcReadonly, IfcVolatile, IfcResetActionstats, IfcPrintActionstats, IfcCountPcode, IfcCallOtherFixup, IfcCallFixup, IfcComment, IfcCallGraphList, IfcCallGraphLoad, IfcCallGraphBuildQuick, IfcCallGraphBuild, IfcCallGraphDump, IfcDuplicateHash, IfcCommentInstr, IfcGraphDom, IfcGraphControlflow, IfcGraphDataflow, IfcPrintRaw, IfcContinue, IfcPrintMap, IfcPrintLocalrange, IfcUnlockPrototype, IfcLockPrototype, IfcPrintInputsAll, IfcPrintInputs, IfcGlobalRegisters, IfcGlobalify, IfcGlobalRemove, IfcGlobalAdd, IfcDeadcodedelay, IfcFlowOverride, IfcJumpOverride, IfcProtooverride, IfcForcegoto, IfcForceDatatypeFormat, IfcForceFormat, IfcTypeVarnode, IfcNameVarnode, IfcVarnodeCover, IfcPrintExtrapop, IfcVarnodehighCover, IfcPrintCover, IfcPrintVarnode, IfcRemove, IfcRetype, IfcRename, IfcPrintParamMeasures, IfcPrintHigh, IfcPrintSpaces, IfcPrintBlocktree, IfcEcho, IfcPrintTree, IfcClosefile, IfcBreakaction, IfcOpenfileAppend, IfcBreakstart, IfcOpenfile, IfcSettrackedrange, IfcHistory, IfcSetcontextrange, IfcQuit, IfcListprototypes, IfcListOverride, IfcListaction, IfcProducePrototypes, IfcProduceC, IfcPrintCTypes, IfcPrintCGlobals, IfcPrintCStruct, IfcPrintCFlat, IfcPrintCXml, IfcPrintLanguage, IfcDecompile, IfcDumpbinary, IfcDump, IfcPrintdisasm, IfcMapconvert, IfcMaplabel, IfcMapexternalref, IfcMapfunction, IfcMaphash, IfcMapaddress, IfcReadSymbols, IfcCleararch, IfaceCommandDummy, IfcAddrrangeLoad, IfcFuncload, IfcAdjustVma, IfcParseFile, IfcParseLine, IfcOption, and IfcSource.
getModule()
virtual string IfaceCommand::getModule (void) const pure virtual
Get the formal module name to which this command belongs.
Commands in the same module share data through their registered IfaceData object
Returns
the formal module name
Implemented in IfaceBaseCommand, IfaceCommandDummy, and IfaceDecompCommand.
Referenced by IfaceStatus::registerCom().
setData()
virtual void IfaceCommand::setData (IfaceStatus * root, IfaceData * data) pure virtual
Associate a specific data object with this command.
Parameters
root is the interface object this command is registered with
data is the data object the command should use
Implemented in IfaceBaseCommand, IfaceCommandDummy, and IfaceDecompCommand.
Referenced by IfaceStatus::registerCom().
The documentation for this class was generated from the following files:
interface.hh
interface.cc