decompiler: TypeArray Class Reference
TypeArray Class Reference
Datatype object representing an array of elements.
#include <type.hh>
Public Member Functions
TypeArray (const TypeArray &op)
Construct from another TypeArray.
TypeArray (int4 n, Datatype *ao)
Construct given an array size and element data-type.
Datatype * getSubEntry (int4 off, int4 sz, int4 *newoff, int4 *el) const
Figure out what a byte range overlaps.
virtual void printRaw (ostream &s) const
Print a description of the type to stream.
virtual Datatype * getSubType (uintb off, uintb *newoff) const
Recover component data-type one-level down.
virtual int4 numDepend (void) const
virtual Datatype * getDepend (int4 index) const
virtual void printNameBase (ostream &s) const
virtual int4 compare (const Datatype &op, int4 level) const
Order types for propagation.
virtual int4 compareDependency (const Datatype &op) const
Compare for storage in tree structure.
virtual Datatype * clone (void) const
Clone the data-type.
virtual void saveXml (ostream &s) const
Serialize the data-type to XML.
virtual Datatype * resolveInFlow (PcodeOp *op, int4 slot)
Tailor data-type propagation based on Varnode use.
virtual Datatype * findResolve (const PcodeOp *op, int4 slot)
Find a previously resolved sub-type.
virtual int4 findCompatibleResolve (Datatype *ct) const
Find a resolution compatible with the given data-type.
Public Member Functions inherited from Datatype
Datatype (const Datatype &op)
Construct the base data-type copying low-level properties of another.
Datatype (int4 s, type_metatype m)
Construct the base data-type providing size and meta-type.
bool hasSameVariableBase (const Datatype *ct) const
Are these the same variable length data-type.
uint4 getDisplayFormat (void) const
Get the display format for constants with this data-type.
virtual Datatype * nearestArrayedComponentForward (uintb off, uintb *newoff, int4 *elSize) const
virtual Datatype * nearestArrayedComponentBackward (uintb off, uintb *newoff, int4 *elSize) const
virtual bool isPtrsubMatching (uintb off) const
Is this data-type suitable as input to a CPUI_PTRSUB op.
virtual Datatype * getStripped (void) const
Get a stripped version of this for formal use in formal declarations.
int4 typeOrderBool (const Datatype &op) const
Order this with -op-, treating bool data-type as special.
void saveXmlRef (ostream &s) const
Write an XML reference of this to stream.
Protected Member Functions
void restoreXml (const Element *el, TypeFactory &typegrp)
TypeArray (void)
Internal constructor for restoreXml.
Protected Member Functions inherited from Datatype
void restoreXmlBasic (const Element *el)
Recover basic data-type properties.
void saveXmlBasic (type_metatype meta, ostream &s) const
Save basic data-type properties.
void saveXmlTypedef (ostream &s) const
Write this as a typedef tag to stream.
void setDisplayFormat (uint4 format)
Set a specific display format.
Protected Attributes
Datatype * arrayof
type of which we have an array
int4 arraysize
Number of elements in the array.
Protected Attributes inherited from Datatype
int4 size
Size (of variable holding a value of this type)
string name
Name of type.
type_metatype metatype
Meta-type - type disregarding size.
sub_metatype submeta
Sub-type of of the meta-type, for comparisons.
uint4 flags
Boolean properties of the type.
uint8 id
A unique id for the type (or 0 if an id is not assigned)
Datatype * typedefImm
The immediate data-type being typedefed by this.
Friends
class TypeFactory
Additional Inherited Members
Static Public Member Functions inherited from Datatype
static uint4 encodeIntegerFormat (const string &val)
Encode the format attribute from an XML element.
static string decodeIntegerFormat (uint4 val)
Decode the given format value into an XML attribute string.
Protected Types inherited from Datatype
enum {
coretype = 1, chartype = 2, enumtype = 4, poweroftwo = 8,
utf16 = 16, utf32 = 32, opaque_string = 64, variable_length = 128,
has_stripped = 0x100, is_ptrrel = 0x200, type_incomplete = 0x400, needs_resolution = 0x800,
force_format = 0x7000
}
Boolean properties of datatypes.
Static Protected Member Functions inherited from Datatype
static uint8 hashName (const string &nm)
Produce a data-type id by hashing the type name.
static uint8 hashSize (uint8 id, int4 size)
Reversibly hash size into id.
Static Protected Attributes inherited from Datatype
static sub_metatype base2sub [14]
Detailed Description
Datatype object representing an array of elements.
Member Function Documentation
compare()
int4 TypeArray::compare (const Datatype & op, int4 level) const virtual
Order types for propagation.
Order this with another data-type, in a way suitable for the type propagation algorithm. Bigger types come earlier. More specific types come earlier.
Parameters
op is the data-type to compare with this
level is maximum level to descend when recursively comparing
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References arrayof, and Datatype::compare().
compareDependency()
int4 TypeArray::compareDependency (const Datatype & op) const virtual
Compare for storage in tree structure.
Sort data-types for the main TypeFactory container. The sort needs to be based on the data-type structure so that an example data-type, constructed outside the factory, can be used to find the equivalent object inside the factory. This means the comparison should not examine the data-type id. In practice, the comparison only needs to go down one level in the component structure before just comparing component pointers.
Parameters
op is the data-type to compare with this
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References arrayof, Datatype::size, and Datatype::submeta.
findCompatibleResolve()
int4 TypeArray::findCompatibleResolve (Datatype * ct) const virtual
Find a resolution compatible with the given data-type.
If this data-type has an alternate data-type form that matches the given data-type, return an index indicating this form, otherwise return -1.
Parameters
ct is the given data-type
Returns
the index of the matching form or -1
Reimplemented from Datatype.
findResolve()
Datatype * TypeArray::findResolve (const PcodeOp * op, int4 slot) virtual
Find a previously resolved sub-type.
This is the constant version of resolveInFlow. If a resulting subtype has already been calculated, for the particular read (slot >= 0) or write (slot == -1), then return it. Otherwise return the original data-type.
Parameters
op is the PcodeOp using the Varnode assigned with this data-type
slot is the slot reading or writing the Varnode
Returns
the resolved subtype or the original data-type
Reimplemented from Datatype.
getSubEntry()
Datatype * TypeArray::getSubEntry (int4 off, int4 sz, int4 * newoff, int4 * el) const
Figure out what a byte range overlaps.
Given some contiguous piece of the array, figure out which element overlaps the piece, and pass back the element index and the renormalized offset
Parameters
off is the offset into the array
sz is the size of the piece (in bytes)
newoff is a pointer to the renormalized offset to pass back
el is a pointer to the array index to pass back
Returns
the element data-type or NULL if the piece overlaps more than one
References arrayof.
getSubType()
Datatype * TypeArray::getSubType (uintb off, uintb * newoff) const virtual
Recover component data-type one-level down.
Given an offset into this data-type, return the component data-type at that offset. Also, pass back a "renormalized" offset suitable for recursize getSubType() calls: i.e. if the original offset hits the exact start of the sub-type, 0 is passed back. If there is no valid component data-type at the offset, return NULL and pass back the original offset
Parameters
off is the offset into this data-type
newoff is a pointer to the passed-back offset
Returns
a pointer to the component data-type or NULL
Reimplemented from Datatype.
References arrayof.
printRaw()
void TypeArray::printRaw (ostream & s) const virtual
Print a description of the type to stream.
Print a raw description of the type to stream. Intended for debugging. Not intended to produce parsable C.
Parameters
s is the output stream
Reimplemented from Datatype.
References arrayof, arraysize, and Datatype::printRaw().
resolveInFlow()
Datatype * TypeArray::resolveInFlow (PcodeOp * op, int4 slot) virtual
Tailor data-type propagation based on Varnode use.
For certain data-types, particularly union, variables of that data-type are transformed into a subtype depending on the particular use. Each read or write of the variable may use a different subtype. This method returns the particular subtype required based on a specific PcodeOp. A slot index >=0 indicates which operand reads the variable, or if the index is -1, the variable is written.
Parameters
op is the specific PcodeOp
slot indicates the input operand, or the output
Returns
the resolved sub-type
Reimplemented from Datatype.
restoreXml()
void TypeArray::restoreXml (const Element * el, TypeFactory & typegrp) protected
Restore this array from an XML element
Parse a <type> tag with a child describing the array element data-type.
Parameters
el is the root XML element
typegrp is the factory owning this data-type
Referenced by TypeFactory::restoreXmlTypeNoRef().
saveXml()
void TypeArray::saveXml (ostream & s) const virtual
Serialize the data-type to XML.
Write out a formal description of the data-type as an XML <type> tag. For composite data-types, the description goes down one level, describing the component types only by reference.
Parameters
s is the stream to write to
Reimplemented from Datatype.
References a_v_i(), arraysize, Datatype::metatype, Datatype::saveXmlBasic(), Datatype::saveXmlTypedef(), and Datatype::typedefImm.
The documentation for this class was generated from the following files:
type.hh
type.cc