decompiler: FunctionTestCollection Class Reference
FunctionTestCollection Class Reference
A collection of tests around a single program/function.
#include <testfunction.hh>
Public Member Functions
FunctionTestCollection (ostream &s)
Constructor.
FunctionTestCollection (IfaceStatus *con)
Constructor with preexisting console.
~FunctionTestCollection (void)
Destructor.
void loadTest (const string &filename)
Load a test program, tests, and script.
void restoreXml (DocumentStorage &store, const Element *el)
Load tests from a <decompilertest> tag.
void restoreXmlOldForm (DocumentStorage &store, const Element *el)
Load tests from <binaryimage> tag.
void runTests (list< string > &lateStream)
Run the script and perform the tests.
Static Public Member Functions
static void runTestFiles (const vector< string > &testFiles, ostream &s)
Run tests for each listed file.
Private Member Functions
void clear (void)
Clear any previous architecture and function.
void restoreXmlCommands (const Element *el)
Reconstruct commands from an XML tag.
void buildProgram (DocumentStorage &store)
Build program (Architecture) from <binaryimage> tag.
void startTests (void) const
Initialize each FunctionTestProperty.
void passLineToTests (const string &line) const
Let all tests analyze a line of the results.
void evaluateTests (list< string > &lateStream) const
Do the final evaluation of each test.
Private Attributes
IfaceDecompData * dcp
Program data for the test collection.
string fileName
Name of the file containing test data.
list< FunctionTestProperty > testList
List of tests for this collection.
vector< string > commands
Sequence of commands for current test.
IfaceStatus * console
Decompiler console for executing scripts.
bool consoleOwner
Set to true if this object owns the console.
int4 numTestsApplied
Count of tests that were executed.
int4 numTestsSucceeded
Count of tests that passed.
Detailed Description
A collection of tests around a single program/function.
The collection of tests is loaded from a single XML file via loadTest(), and the tests are run by calling runTests(). An entire program is loaded and possibly annotated by a series of console command lines. Decompiler output is also triggered by a command, and then the output is scanned for by the test objects (FunctionTestProperty). Results of passed/failed tests are collected. If the command line script does not complete properly, this is considered a special kind of failure.
Constructor & Destructor Documentation
FunctionTestCollection()
FunctionTestCollection::FunctionTestCollection (ostream & s)
Constructor.
Parameters
s is the stream where output is sent during tests
References commands, console, consoleOwner, dcp, IfaceStatus::getData(), numTestsApplied, and numTestsSucceeded.
Member Function Documentation
buildProgram()
void FunctionTestCollection::buildProgram (DocumentStorage & store) private
Build program (Architecture) from <binaryimage> tag.
Instantiate an Architecture object.
References ArchitectureCapability::buildArchitecture(), IfaceDecompData::conf, console, dcp, LowlevelError::explain, XmlError::explain, ArchitectureCapability::getCapability(), Architecture::init(), IfaceStatus::optr, and Architecture::readLoaderSymbols().
Referenced by restoreXml().
evaluateTests()
void FunctionTestCollection::evaluateTests (list< string > & lateStream) const private
Do the final evaluation of each test.
This is called after each test has been fed all lines of output. The result of each test is printed to the midStream, and then failures are written to the lateStream in order to see a summary.
Parameters
lateStream collects failures to display as a summary
References console, numTestsApplied, numTestsSucceeded, IfaceStatus::optr, and testList.
Referenced by runTests().
loadTest()
void FunctionTestCollection::loadTest (const string & filename)
Load a test program, tests, and script.
Load the architecture based on the discovered <binaryimage> tag. Collect the script commands and the specific tests.
Parameters
filename is the XML file holding the test data
References fileName, DocumentStorage::openDocument(), restoreXml(), and restoreXmlOldForm().
Referenced by IfcLoadTestFile::execute(), and runTestFiles().
passLineToTests()
void FunctionTestCollection::passLineToTests (const string & line) const private
Let all tests analyze a line of the results.
Each test gets a chance to process a line of output
Parameters
line is the given line of output
References testList.
Referenced by runTests().
restoreXmlCommands()
void FunctionTestCollection::restoreXmlCommands (const Element * el) private
Reconstruct commands from an XML tag.
Parameters
el is the root <script> tag
References commands.
Referenced by restoreXml().
restoreXmlOldForm()
void FunctionTestCollection::restoreXmlOldForm (DocumentStorage & store, const Element * el)
Load tests from <binaryimage> tag.
Pull the script and tests from a comment in <binaryimage>
Referenced by loadTest().
runTestFiles()
void FunctionTestCollection::runTestFiles (const vector< string > & testFiles, ostream & s) static
Run tests for each listed file.
Run through all XML files in the given list, processing each in turn.
Parameters
testFiles is the given list of test files
s is the output stream to print results to
References clear(), IfaceError::explain, loadTest(), and runTests().
runTests()
void FunctionTestCollection::runTests (list< string > & lateStream)
Run the script and perform the tests.
Run the script commands on the current program. Collect any bulk output, and run tests over the output. Report test failures back to the caller
Parameters
lateStream collects messages for a final summary
References console, evaluateTests(), fileName, IfaceStatus::fileoptr, mainloop(), numTestsApplied, numTestsSucceeded, IfaceStatus::optr, passLineToTests(), and startTests().
Referenced by runTestFiles().
startTests()
void FunctionTestCollection::startTests (void) const private
Initialize each FunctionTestProperty.
Let each test initialize itself thru its startTest() method.
References testList.
Referenced by runTests().
The documentation for this class was generated from the following files:
testfunction.hh
testfunction.cc