decompiler: TypeField Class Reference
TypeField Class Reference
A field within a structure or union.
#include <type.hh>
Public Member Functions
TypeField (const Element *el, TypeFactory &typegrp)
Restore this field from an XML stream.
void saveXml (ostream &s) const
Save this field as XML.
Public Attributes
int4 ident
Id for identifying this within its containing structure or union.
int4 offset
Offset (into containing structure or union) of subfield.
string name
Name of subfield.
Datatype * type
Data-type of subfield.
Detailed Description
A field within a structure or union.
Constructor & Destructor Documentation
TypeField()
TypeField::TypeField (const Element * el, TypeFactory & typegrp)
Restore this field from an XML stream.
Contruct from the given <field> element.
Parameters
el is the element
typegrp is the TypeFactory for parsing data-type info
References Element::getAttributeValue(), ident, name, offset, TypeFactory::restoreXmlType(), and type.
Member Function Documentation
saveXml()
void TypeField::saveXml (ostream & s) const
Save this field as XML.
Write out a formal description of this as an XML <field> tag.
Parameters
s is the stream to write to
References a_v(), a_v_i(), ident, name, and offset.
The documentation for this class was generated from the following files:
type.hh
type.cc