decompiler: HeritageInfo Class Reference
HeritageInfo Class Reference
Information about heritage passes performed for a specific address space.
#include <heritage.hh>
Public Member Functions
HeritageInfo (AddrSpace *spc)
Constructor.
Private Member Functions
void reset (void)
Reset the state.
Private Attributes
AddrSpace * space
The address space this record describes.
int4 delay
How many passes to delay heritage of this space.
int4 deadcodedelay
How many passes to delay deadcode removal of this space.
int4 deadremoved
>0 if Varnodes in this space have been eliminated
bool loadGuardSearch
true if the search for LOAD ops to guard has been performed
bool warningissued
true if warning issued previously
bool hasCallPlaceholders
true for the stack space, if stack placeholders have not been removed
Friends
class Heritage
Detailed Description
Information about heritage passes performed for a specific address space.
For a particular address space, this keeps track of:
how long to delay heritage
how long to delay dead code removal
whether dead code has been removed (for this space)
have warnings been issued
Constructor & Destructor Documentation
HeritageInfo()
HeritageInfo::HeritageInfo (AddrSpace * spc)
Constructor.
Initialize heritage state information for a particular address space
Parameters
spc is the address space
References deadcodedelay, deadremoved, delay, AddrSpace::getDeadcodeDelay(), AddrSpace::getDelay(), AddrSpace::getType(), hasCallPlaceholders, IPTR_SPACEBASE, AddrSpace::isHeritaged(), loadGuardSearch, space, and warningissued.
The documentation for this class was generated from the following files:
heritage.hh
heritage.cc