decompiler: Datatype Class Reference
Datatype Class Reference abstract
The base datatype class for the decompiler.
#include <type.hh>
Public Member Functions
Datatype (const Datatype &op)
Construct the base data-type copying low-level properties of another.
Datatype (int4 s, type_metatype m)
Construct the base data-type providing size and meta-type.
bool hasSameVariableBase (const Datatype *ct) const
Are these the same variable length data-type.
uint4 getDisplayFormat (void) const
Get the display format for constants with this data-type.
virtual void printRaw (ostream &s) const
Print a description of the type to stream.
virtual Datatype * getSubType (uintb off, uintb *newoff) const
Recover component data-type one-level down.
virtual Datatype * nearestArrayedComponentForward (uintb off, uintb *newoff, int4 *elSize) const
virtual Datatype * nearestArrayedComponentBackward (uintb off, uintb *newoff, int4 *elSize) const
virtual int4 compare (const Datatype &op, int4 level) const
Order types for propagation.
virtual int4 compareDependency (const Datatype &op) const
Compare for storage in tree structure.
virtual void saveXml (ostream &s) const
Serialize the data-type to XML.
virtual bool isPtrsubMatching (uintb off) const
Is this data-type suitable as input to a CPUI_PTRSUB op.
virtual Datatype * getStripped (void) const
Get a stripped version of this for formal use in formal declarations.
virtual Datatype * resolveInFlow (PcodeOp *op, int4 slot)
Tailor data-type propagation based on Varnode use.
virtual Datatype * findResolve (const PcodeOp *op, int4 slot)
Find a previously resolved sub-type.
virtual int4 findCompatibleResolve (Datatype *ct) const
Find a resolution compatible with the given data-type.
int4 typeOrderBool (const Datatype &op) const
Order this with -op-, treating bool data-type as special.
void saveXmlRef (ostream &s) const
Write an XML reference of this to stream.
Static Public Member Functions
static uint4 encodeIntegerFormat (const string &val)
Encode the format attribute from an XML element.
static string decodeIntegerFormat (uint4 val)
Decode the given format value into an XML attribute string.
Protected Types
enum {
coretype = 1, chartype = 2, enumtype = 4, poweroftwo = 8,
utf16 = 16, utf32 = 32, opaque_string = 64, variable_length = 128,
has_stripped = 0x100, is_ptrrel = 0x200, type_incomplete = 0x400, needs_resolution = 0x800,
force_format = 0x7000
}
Boolean properties of datatypes.
Protected Member Functions
void restoreXmlBasic (const Element *el)
Recover basic data-type properties.
void saveXmlBasic (type_metatype meta, ostream &s) const
Save basic data-type properties.
void saveXmlTypedef (ostream &s) const
Write this as a typedef tag to stream.
void setDisplayFormat (uint4 format)
Set a specific display format.
virtual Datatype * clone (void) const =0
Clone the data-type.
Static Protected Member Functions
static uint8 hashName (const string &nm)
Produce a data-type id by hashing the type name.
static uint8 hashSize (uint8 id, int4 size)
Reversibly hash size into id.
Protected Attributes
int4 size
Size (of variable holding a value of this type)
string name
Name of type.
type_metatype metatype
Meta-type - type disregarding size.
sub_metatype submeta
Sub-type of of the meta-type, for comparisons.
uint4 flags
Boolean properties of the type.
uint8 id
A unique id for the type (or 0 if an id is not assigned)
Datatype * typedefImm
The immediate data-type being typedefed by this.
Static Protected Attributes
static sub_metatype base2sub [14]
Friends
class TypeFactory
struct DatatypeCompare
Detailed Description
The base datatype class for the decompiler.
Used for symbols, function prototypes, type propagation etc.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Boolean properties of datatypes.
Enumerator
coretype
This is a basic type which will never be redefined.
chartype
ASCII character data.
enumtype
An enumeration type (as well as an integer)
poweroftwo
An enumeration type where all values are of 2^^n form.
utf16
16-bit wide chars in unicode UTF16
utf32
32-bit wide chars in unicode UTF32
opaque_string
Structure that should be treated as a string.
variable_length
May be other structures with same name different lengths.
has_stripped
Datatype has a stripped form for formal declarations.
is_ptrrel
Datatype is a TypePointerRel.
type_incomplete
Set if this (recursive) data-type has not been fully defined yet.
needs_resolution
Datatype (union, pointer to union) needs resolution before propagation.
force_format
3-bits encoding display format, 0=none, 1=hex, 2=dec, 3=oct, 4=bin, 5=char
Member Function Documentation
compare()
int4 Datatype::compare (const Datatype & op, int4 level) const virtual
Order types for propagation.
Order this with another data-type, in a way suitable for the type propagation algorithm. Bigger types come earlier. More specific types come earlier.
Parameters
op is the data-type to compare with this
level is maximum level to descend when recursively comparing
Returns
negative, 0, positive depending on ordering of types
Reimplemented in TypeSpacebase, TypeCode, TypeUnion, TypeStruct, TypeEnum, TypeArray, and TypePointer.
References size, and submeta.
Referenced by TypeArray::compare(), TypeCode::compare(), DatatypeNameCompare::operator()(), and typeOrderBool().
compareDependency()
int4 Datatype::compareDependency (const Datatype & op) const virtual
Compare for storage in tree structure.
Sort data-types for the main TypeFactory container. The sort needs to be based on the data-type structure so that an example data-type, constructed outside the factory, can be used to find the equivalent object inside the factory. This means the comparison should not examine the data-type id. In practice, the comparison only needs to go down one level in the component structure before just comparing component pointers.
Parameters
op is the data-type to compare with this
Returns
negative, 0, positive depending on ordering of types
Reimplemented in TypeSpacebase, TypeCode, TypePointerRel, TypeUnion, TypeStruct, TypeEnum, TypeArray, and TypePointer.
References size, and submeta.
Referenced by TypeCode::compareDependency(), TypeSpacebase::compareDependency(), TypeFactory::findAdd(), DatatypeCompare::operator()(), TypeFactory::restoreCode(), TypeFactory::restoreStruct(), and TypeFactory::restoreUnion().
decodeIntegerFormat()
string Datatype::decodeIntegerFormat (uint4 val) static
Decode the given format value into an XML attribute string.
Possible encoded values are 1-5 corresponding to "hex", "dec", "oct", "bin", "char"
Parameters
val is the value to decode
Returns
the decoded string
Referenced by saveXmlBasic(), Symbol::saveXmlHeader(), and saveXmlTypedef().
encodeIntegerFormat()
uint4 Datatype::encodeIntegerFormat (const string & val) static
Encode the format attribute from an XML element.
Possible values are:
1 - hex
2 - dec
3 - oct
4 - bin
5 - char
Parameters
val is the string to encode
Returns
the encoded value
Referenced by IfcForceFormat::execute(), IfcForceDatatypeFormat::execute(), TypeFactory::restoreTypedef(), restoreXmlBasic(), and Symbol::restoreXmlHeader().
findCompatibleResolve()
int4 Datatype::findCompatibleResolve (Datatype * ct) const virtual
Find a resolution compatible with the given data-type.
If this data-type has an alternate data-type form that matches the given data-type, return an index indicating this form, otherwise return -1.
Parameters
ct is the given data-type
Returns
the index of the matching form or -1
Reimplemented in TypeUnion, TypeStruct, and TypeArray.
Referenced by ActionSetCasts::tryResolutionAdjustment().
findResolve()
Datatype * Datatype::findResolve (const PcodeOp * op, int4 slot) virtual
Find a previously resolved sub-type.
This is the constant version of resolveInFlow. If a resulting subtype has already been calculated, for the particular read (slot >= 0) or write (slot == -1), then return it. Otherwise return the original data-type.
Parameters
op is the PcodeOp using the Varnode assigned with this data-type
slot is the slot reading or writing the Varnode
Returns
the resolved subtype or the original data-type
Reimplemented in TypeUnion, TypeStruct, TypeArray, and TypePointer.
Referenced by ActionSetCasts::castOutput(), Varnode::getHighTypeDefFacing(), Varnode::getHighTypeReadFacing(), Varnode::getTypeDefFacing(), Varnode::getTypeReadFacing(), and PrintC::pushPartialSymbol().
getDisplayFormat()
uint4 Datatype::getDisplayFormat (void) const inline
Get the display format for constants with this data-type.
A non-zero result indicates the type of formatting that is forced on the constant. One of the following values is returned.
1 for hexadecimal
2 for decimal
3 for octal
4 for binary
5 for char
Returns
the forced encoding type or zero
References flags, and force_format.
Referenced by saveXmlBasic(), and saveXmlTypedef().
getStripped()
Datatype * Datatype::getStripped (void) const virtual
Get a stripped version of this for formal use in formal declarations.
Some data-types are ephemeral, and, in the final decompiler output, get replaced with a formal version that is a stripped down version of the original. This method returns this stripped down version, if it exists, or null otherwise. A non-null return should correspond with hasStripped returning true.
Returns
the stripped version or null
Referenced by TypeFactory::getTypePointer(), TypeFactory::getTypePointerStripArray(), and HighVariable::updateType().
getSubType()
Datatype * Datatype::getSubType (uintb off, uintb * newoff) const virtual
Recover component data-type one-level down.
Given an offset into this data-type, return the component data-type at that offset. Also, pass back a "renormalized" offset suitable for recursize getSubType() calls: i.e. if the original offset hits the exact start of the sub-type, 0 is passed back. If there is no valid component data-type at the offset, return NULL and pass back the original offset
Parameters
off is the offset into this data-type
newoff is a pointer to the passed-back offset
Returns
a pointer to the component data-type or NULL
Reimplemented in TypeSpacebase, TypeCode, TypeStruct, and TypeArray.
Referenced by RuleStructOffset0::applyOp(), Funcdata::checkSymbolType(), ScoreUnionFields::derefPointer(), TypePointerRel::getPtrToFromParent(), SymbolEntry::getSizedType(), AddTreeState::hasMatchingSubType(), TypePointer::isPtrsubMatching(), ActionInferTypes::propagateRef(), RangeHint::reconcile(), and ScoreUnionFields::scoreTruncation().
hashName()
uint8 Datatype::hashName (const string & nm) static protected
Produce a data-type id by hashing the type name.
If a type id is explicitly provided for a data-type, this routine is used to produce an id based on a hash of the name. IDs produced this way will have their sign-bit set to distinguish it from other IDs.
Parameters
nm is the type name to be hashed
Referenced by TypeFactory::getBase(), TypeFactory::getTypeChar(), TypeFactory::getTypeCode(), TypeFactory::getTypedef(), TypeFactory::getTypeEnum(), TypeFactory::getTypePointer(), TypeFactory::getTypePointerRel(), TypeFactory::getTypePointerWithSpace(), TypeFactory::getTypeStruct(), TypeFactory::getTypeUnicode(), TypeFactory::getTypeUnion(), TypeFactory::getTypeVoid(), TypeFactory::restoreTypedef(), restoreXmlBasic(), TypeFactory::restoreXmlType(), and TypeFactory::setName().
hashSize()
uint8 Datatype::hashSize (uint8 id, int4 size) static protected
Reversibly hash size into id.
This allows IDs for variable length structures to be uniquefied based on size. A base ID is given and a size of the specific instance. A unique ID is returned. The hashing is reversible by feeding the output ID back into this function with the same size.
Parameters
id is the given ID to (de)uniquify
size is the instance size of the structure
Returns
the (de)uniquified id
References id, and size.
Referenced by TypeFactory::findById(), hasSameVariableBase(), TypeFactory::restoreTypedef(), restoreXmlBasic(), saveXmlBasic(), and saveXmlRef().
hasSameVariableBase()
bool Datatype::hasSameVariableBase (const Datatype * ct) const
Are these the same variable length data-type.
If this and the other given data-type are both variable length and come from the the same base data-type, return true.
Parameters
ct is the other given data-type to compare with this
Returns
true if they are the same variable length data-type.
References hashSize(), id, and size.
Referenced by CastStrategyC::castStandard().
isPtrsubMatching()
bool Datatype::isPtrsubMatching (uintb off) const virtual
Is this data-type suitable as input to a CPUI_PTRSUB op.
A CPUI_PTRSUB must act on a pointer data-type where the given offset addresses a component. Perform this check.
Parameters
off is the given offset
Returns
true if this is a suitable PTRSUB data-type
Reimplemented in TypePointerRel, and TypePointer.
Referenced by RulePtrsubUndo::applyOp().
nearestArrayedComponentBackward()
Datatype * Datatype::nearestArrayedComponentBackward (uintb off, uintb * newoff, int4 * elSize) const virtual
Find the first component data-type before the given offset that is (or contains) an array, and pass back the difference between the component's start and the given offset. Return the component data-type or null if no array is found.
Parameters
off is the given offset into this data-type
newoff is used to pass back the offset difference
elSize is used to pass back the array element size
Returns
the component data-type or null
Reimplemented in TypeSpacebase, and TypeStruct.
Referenced by AddTreeState::hasMatchingSubType(), and TypeSpacebase::nearestArrayedComponentBackward().
nearestArrayedComponentForward()
Datatype * Datatype::nearestArrayedComponentForward (uintb off, uintb * newoff, int4 * elSize) const virtual
Find the first component data-type after the given offset that is (or contains) an array, and pass back the difference between the component's start and the given offset. Return the component data-type or null if no array is found.
Parameters
off is the given offset into this data-type
newoff is used to pass back the offset difference
elSize is used to pass back the array element size
Returns
the component data-type or null
Reimplemented in TypeSpacebase, and TypeStruct.
Referenced by AddTreeState::hasMatchingSubType(), and TypeSpacebase::nearestArrayedComponentForward().
printRaw()
void Datatype::printRaw (ostream & s) const virtual
Print a description of the type to stream.
Print a raw description of the type to stream. Intended for debugging. Not intended to produce parsable C.
Parameters
s is the output stream
Reimplemented in TypeCode, TypePointerRel, TypeArray, and TypePointer.
References name, and size.
Referenced by MapState::addRange(), TypeFactory::insert(), HighVariable::printInfo(), Varnode::printInfo(), TypeArray::printRaw(), and TypePointerRel::printRaw().
resolveInFlow()
Datatype * Datatype::resolveInFlow (PcodeOp * op, int4 slot) virtual
Tailor data-type propagation based on Varnode use.
For certain data-types, particularly union, variables of that data-type are transformed into a subtype depending on the particular use. Each read or write of the variable may use a different subtype. This method returns the particular subtype required based on a specific PcodeOp. A slot index >=0 indicates which operand reads the variable, or if the index is -1, the variable is written.
Parameters
op is the specific PcodeOp
slot indicates the input operand, or the output
Returns
the resolved sub-type
Reimplemented in TypeUnion, TypeStruct, TypeArray, and TypePointer.
Referenced by ActionInferTypes::propagateTypeEdge().
restoreXmlBasic()
void Datatype::restoreXmlBasic (const Element * el) protected
Recover basic data-type properties.
Restore the basic properties (name,size,id) of a data-type from an XML element Properties are read from the attributes of the element
Parameters
el is the XML element
References base2sub, coretype, encodeIntegerFormat(), flags, Element::getAttributeValue(), hashName(), hashSize(), id, metatype, name, opaque_string, setDisplayFormat(), size, string2metatype(), submeta, variable_length, and xml_readbool().
Referenced by TypeFactory::restoreStruct(), TypeCode::restoreStub(), TypeFactory::restoreUnion(), TypeFactory::restoreXmlTypeNoRef(), and TypeFactory::restoreXmlTypeWithCodeFlags().
saveXml()
void Datatype::saveXml (ostream & s) const virtual
Serialize the data-type to XML.
Write out a formal description of the data-type as an XML <type> tag. For composite data-types, the description goes down one level, describing the component types only by reference.
Parameters
s is the stream to write to
Reimplemented in TypeSpacebase, TypeCode, TypePointerRel, TypeUnion, TypeStruct, TypeEnum, TypeArray, TypePointer, TypeVoid, TypeUnicode, and TypeChar.
References metatype, and saveXmlBasic().
Referenced by CPoolRecord::saveXml(), TypePointerRel::saveXml(), ProtoStoreInternal::saveXml(), FuncProto::saveXml(), TypeFactory::saveXmlCoreTypes(), and saveXmlRef().
saveXmlBasic()
void Datatype::saveXmlBasic (type_metatype meta, ostream & s) const protected
Save basic data-type properties.
Write out basic data-type properties (name,size,id) as XML attributes. This routine presumes the initial tag is already written to the stream.
Parameters
meta is the metatype to put in the XML
s is the stream to write to
References a_v(), a_v_b(), a_v_i(), coretype, decodeIntegerFormat(), flags, getDisplayFormat(), hashSize(), id, metatype2string(), name, opaque_string, and size.
Referenced by saveXml(), TypeArray::saveXml(), TypePointerRel::saveXml(), TypeCode::saveXml(), and TypeSpacebase::saveXml().
saveXmlRef()
void Datatype::saveXmlRef (ostream & s) const
Write an XML reference of this to stream.
Write a simple reference to this data-type as an XML <typeref> tag, which only encodes the name and id.
Parameters
s is the stream to write to
References a_v(), a_v_i(), a_v_u(), hashSize(), metatype, name, saveXml(), size, and TYPE_VOID.
Referenced by TypePointerRel::saveXml(), Symbol::saveXmlBody(), and saveXmlTypedef().
saveXmlTypedef()
void Datatype::saveXmlTypedef (ostream & s) const protected
Write this as a typedef tag to stream.
Called only if the typedefImm field is non-null. Write the data-type to the stream as a simple <typedef> tag including only the names and ids of this and the data-type it typedefs.
Parameters
s is the output stream
References a_v(), a_v_u(), decodeIntegerFormat(), getDisplayFormat(), name, saveXmlRef(), and typedefImm.
Referenced by TypeArray::saveXml(), TypeCode::saveXml(), and TypeSpacebase::saveXml().
setDisplayFormat()
void Datatype::setDisplayFormat (uint4 format) inline protected
Set a specific display format.
The display format for the data-type is changed based on the given format. A value of zero clears any preexisting format. Otherwise the value can be one of: 1=hex, 2=dec, 3=oct, 4=bin, 5=char
Parameters
format is the given format
References flags, and force_format.
Referenced by TypeFactory::getTypedef(), restoreXmlBasic(), and TypeFactory::setDisplayFormat().
typeOrderBool()
int4 Datatype::typeOrderBool (const Datatype & op) const inline
Order this with -op-, treating bool data-type as special.
Order data-types, with special handling of the bool data-type. Data-types are compared using the normal ordering, but bool is ordered after all other data-types. A return value of 0 indicates the data-types are the same, -1 indicates that this is prefered (ordered earlier), and 1 indicates this is ordered later.
Parameters
op is the other data-type to compare with this
Returns
-1, 0, or 1
References compare(), metatype, and TYPE_BOOL.
Member Data Documentation
base2sub
sub_metatype Datatype::base2sub static protected
Initial value:
= {
    SUB_UNION, SUB_STRUCT, SUB_PARTIALSTRUCT, SUB_ARRAY, SUB_PTRREL, SUB_PTR, SUB_FLOAT, SUB_CODE, SUB_BOOL,
    SUB_UINT_PLAIN, SUB_INT_PLAIN, SUB_UNKNOWN, SUB_SPACEBASE, SUB_VOID
}
The base propagation ordering associated with each meta-type. The array elements correspond to the ordering of type_metatype.
Referenced by Datatype(), and restoreXmlBasic().
The documentation for this class was generated from the following files:
type.hh
type.cc