decompiler: IfaceStatus Class Reference
IfaceStatus Class Reference abstract
A generic console mode interface and command executor.
#include <interface.hh>
Public Member Functions
IfaceStatus (const string &prmpt, ostream &os, int4 mxhist=10)
Constructor.
virtual ~IfaceStatus (void)
Destructor.
void pushScript (const string &filename, const string &newprompt)
Push a new file on the script stack.
virtual void pushScript (istream *iptr, const string &newprompt)
Provide a new input stream to execute, with an associated command prompt.
virtual void popScript (void)
Return to processing the parent stream.
virtual void reset (void)
Pop any existing script streams and return to processing from the base stream.
void registerCom (IfaceCommand *fptr, const char *nm1, const char *nm2=(const char *) 0, const char *nm3=(const char *) 0, const char *nm4=(const char *) 0, const char *nm5=(const char *) 0)
Register a command with this interface.
IfaceData * getData (const string &nm) const
Get data associated with a IfaceCommand module.
bool runCommand (void)
Run the next command.
void getHistory (string &line, int4 i) const
Get the i-th command line from history.
virtual bool isStreamFinished (void) const =0
Return true if the current stream is finished.
void evaluateError (void)
Adjust which stream to process based on last error.
Static Public Member Functions
static void wordsToString (string &res, const vector< string > &list)
Concatenate tokens.
Public Attributes
bool done
Set to true (by a command) to indicate processing is finished.
ostream * optr
Where to put command line output.
ostream * fileoptr
Where to put bulk output.
Protected Member Functions
int4 expandCom (vector< string > &expand, istream &s, vector< IfaceCommand * >::const_iterator &first, vector< IfaceCommand * >::const_iterator &last)
Expand tokens from the given input stream to a full command.
Protected Attributes
bool inerror
Set to true if last command did not succeed.
vector< IfaceCommand * > comlist
List of registered commands.
map< string, IfaceData * > datamap
Data associated with particular modules.
Private Member Functions
void restrictCom (vector< IfaceCommand * >::const_iterator &first, vector< IfaceCommand * >::const_iterator &last, vector< string > &input)
Restrict range of possible commands given a list of command line tokens.
virtual void readLine (string &line)=0
Read the next command line.
void saveHistory (const string &line)
Store the given command line into history.
Private Attributes
vector< string > promptstack
Stack of command prompts corresponding to script nesting level.
vector< uint4 > flagstack
Stack of flag state corresponding to script nesting level.
string prompt
The current command prompt.
int4 maxhistory
Maximum number of command lines to store in history.
int4 curhistory
Most recent history.
vector< string > history
History of commands executed through this interface.
bool sorted
Set to true if commands are sorted.
bool errorisdone
Set to true if any error terminates the process.
Detailed Description
A generic console mode interface and command executor.
Input is provided one command line at a time by providing calling readLine(). Output goes to a provided ostream, optr. Output to a separate bulk stream can be enabled by setting fileoptr.
A derived IfaceCommand is attached to a command string via registerCom() i.e. stat.registerCom(new IfcQuit(),"quit"); stat.registerCom(new IfcOpenfileAppend(),"openfile","append"); stat.mainloop(); Command line processing is started with mainloop(), which prints a command prompt, allows command line editing, including command completion and history, and executes the corresponding IfaceComman::execute() callback. Command words only have to match enough to disambiguate it from other commands. A Custom history size and command prompt can be passed to the constructor. Applications should inherit from base class IfaceStatus in order to
Override the readLine() method
Override pushScript() and popScript() to allow command scripts
Get custom data into IfaceCommand callbacks
Constructor & Destructor Documentation
IfaceStatus()
IfaceStatus::IfaceStatus (const string & prmpt, ostream & os, int4 mxhist = 10)
Constructor.
Parameters
prmpt is the base command line prompt
os is the base stream to write output to
mxhist is the maximum number of lines to store in history
References curhistory, done, errorisdone, fileoptr, inerror, maxhistory, optr, prompt, and sorted.
Member Function Documentation
expandCom()
int4 IfaceStatus::expandCom (vector< string > & expand, istream & s, vector< IfaceCommand * >::const_iterator & first, vector< IfaceCommand * >::const_iterator & last) protected
Expand tokens from the given input stream to a full command.
A range of possible commands is returned. Processing of the stream stops as soon as at least one complete command is recognized. Tokens partially matching a command are expanded to the full command and passed back.
Parameters
expand will hold the list of expanded tokens
s is the input stream tokens are read from
first will hold the beginning of the matching range of commands
last will hold the end of the matching range of commands
Returns
the number of matching commands
References restrictCom().
Referenced by IfaceTerm::doCompletion(), and runCommand().
getData()
IfaceData * IfaceStatus::getData (const string & nm) const
Get data associated with a IfaceCommand module.
Commands (IfaceCommand) are associated with a particular module that has a formal name and a data object associated with it. This method retrieves the module specific data object by name.
Parameters
nm is the name of the module
Returns
the IfaceData object or null
References datamap.
Referenced by FunctionTestCollection::FunctionTestCollection(), and mainloop().
getHistory()
void IfaceStatus::getHistory (string & line, int4 i) const
Get the i-th command line from history.
A command line is selected by specifying how many steps in time to go back through the list of successful command lines.
Parameters
line will hold the selected command line from history
i is the number of steps back to go
References curhistory, history, and maxhistory.
Referenced by IfcHistory::execute(), and IfaceTerm::readLine().
popScript()
void IfaceStatus::popScript (void) virtual
Return to processing the parent stream.
The current input stream, as established by a script, is popped from the stack, along with its command prompt, and processing continues with the previous stream.
Reimplemented in IfaceTerm.
References errorisdone, flagstack, inerror, prompt, and promptstack.
Referenced by mainloop(), IfaceTerm::popScript(), reset(), and ~IfaceStatus().
pushScript() [1/2]
void IfaceStatus::pushScript (const string & filename, const string & newprompt)
Push a new file on the script stack.
Attempt to open the file, and if we succeed put the open stream onto the script stack.
Parameters
filename is the name of the script file
newprompt is the command line prompt to associate with the file
Referenced by IfcSource::execute(), IfcExecuteTestCommand::execute(), and IfaceTerm::pushScript().
pushScript() [2/2]
void IfaceStatus::pushScript (istream * iptr, const string & newprompt) virtual
Provide a new input stream to execute, with an associated command prompt.
The new stream is added to a stack and becomes the primary source for parsing new commands. Once commands from the stream are exhausted, parsing will resume in the previous stream.
Parameters
iptr is the new input stream
newprompt is the command line prompt to associate with the new stream
Reimplemented in IfaceTerm.
References errorisdone, flagstack, prompt, and promptstack.
readLine()
virtual void IfaceStatus::readLine (string & line) private pure virtual
Read the next command line.
Parameters
line is filled in with the next command to execute
Implemented in ConsoleCommands, and IfaceTerm.
Referenced by runCommand().
registerCom()
void IfaceStatus::registerCom (IfaceCommand * fptr, const char * nm1, const char * nm2 = (const char *)0, const char * nm3 = (const char *)0, const char * nm4 = (const char *)0, const char * nm5 = (const char *)0)
Register a command with this interface.
A command object is associated with one or more tokens on the command line. A string containing up to 5 tokens can be associated with the command.
Parameters
fptr is the IfaceCommand object
nm1 is the first token representing the command
nm2 is the second token (or null)
nm3 is the third token (or null)
nm4 is the fourth token (or null)
nm5 is the fifth token (or null)
References IfaceCommand::addWord(), comlist, IfaceCommand::createData(), datamap, IfaceCommand::getModule(), IfaceCommand::setData(), and sorted.
Referenced by IfaceDecompCapability::registerCommands().
restrictCom()
void IfaceStatus::restrictCom (vector< IfaceCommand * >::const_iterator & first, vector< IfaceCommand * >::const_iterator & last, vector< string > & input) private
Restrict range of possible commands given a list of command line tokens.
Given a set of tokens partially describing a command, provide the most narrow range of IfaceCommand objects that could be referred to.
Parameters
first will hold an iterator to the first command in the range
last will hold an iterator (one after) the last command in the range
input is the list of command tokens to match on
References IfaceCommand::addWord(), IfaceCommand::addWords(), and compare_ifacecommand().
Referenced by expandCom().
runCommand()
bool IfaceStatus::runCommand (void)
Run the next command.
A single command line is read (via readLine) and executed. If the command is successfully executed, the command line is committed to history and true is returned.
Returns
true if a command successfully executes
References comlist, compare_ifacecommand(), expandCom(), optr, readLine(), saveHistory(), and sorted.
Referenced by execute().
saveHistory()
void IfaceStatus::saveHistory (const string & line) private
Store the given command line into history.
The line is saved in a circular history buffer
Parameters
line is the command line to save
References curhistory, history, and maxhistory.
Referenced by runCommand().
wordsToString()
void IfaceStatus::wordsToString (string & res, const vector< string > & list) static
Concatenate tokens.
Concatenate a list of tokens into a single string, separated by a space character.
Referenced by IfaceCommand::commandString(), and IfaceTerm::doCompletion().
The documentation for this class was generated from the following files:
interface.hh
interface.cc