decompiler: IfaceTerm Class Reference
IfaceTerm Class Reference
Implement the command-line interface on top of a specific input stream.
#include <ifaceterm.hh>
Public Member Functions
IfaceTerm (const string &prmpt, istream &is, ostream &os)
Constructor.
virtual void pushScript (istream *iptr, const string &newprompt)
Provide a new input stream to execute, with an associated command prompt.
virtual void popScript (void)
Return to processing the parent stream.
virtual bool isStreamFinished (void) const
Return true if the current stream is finished.
Public Member Functions inherited from IfaceStatus
IfaceStatus (const string &prmpt, ostream &os, int4 mxhist=10)
Constructor.
virtual ~IfaceStatus (void)
Destructor.
void pushScript (const string &filename, const string &newprompt)
Push a new file on the script stack.
virtual void reset (void)
Pop any existing script streams and return to processing from the base stream.
void registerCom (IfaceCommand *fptr, const char *nm1, const char *nm2=(const char *) 0, const char *nm3=(const char *) 0, const char *nm4=(const char *) 0, const char *nm5=(const char *) 0)
Register a command with this interface.
IfaceData * getData (const string &nm) const
Get data associated with a IfaceCommand module.
bool runCommand (void)
Run the next command.
void getHistory (string &line, int4 i) const
Get the i-th command line from history.
void evaluateError (void)
Adjust which stream to process based on last error.
Private Member Functions
int4 doCompletion (string &line, int4 cursor)
'Complete' the current command line
virtual void readLine (string &line)
Read the next command line.
Private Attributes
istream * sptr
The base input stream for the interface.
vector< istream * > inputstack
Stack of nested input streams.
Additional Inherited Members
Static Public Member Functions inherited from IfaceStatus
static void wordsToString (string &res, const vector< string > &list)
Concatenate tokens.
Public Attributes inherited from IfaceStatus
bool done
Set to true (by a command) to indicate processing is finished.
ostream * optr
Where to put command line output.
ostream * fileoptr
Where to put bulk output.
Protected Member Functions inherited from IfaceStatus
int4 expandCom (vector< string > &expand, istream &s, vector< IfaceCommand * >::const_iterator &first, vector< IfaceCommand * >::const_iterator &last)
Expand tokens from the given input stream to a full command.
Protected Attributes inherited from IfaceStatus
bool inerror
Set to true if last command did not succeed.
vector< IfaceCommand * > comlist
List of registered commands.
map< string, IfaceData * > datamap
Data associated with particular modules.
Detailed Description
Implement the command-line interface on top of a specific input stream.
An initial input stream is provided as the base stream to parse for commands. Additional input streams can be stacked by invoking scripts. If the stream supports it, the stream parser recognizes special command-line editing and completion keys.
Member Function Documentation
doCompletion()
int4 IfaceTerm::doCompletion (string & line, int4 cursor) private
'Complete' the current command line
Respond to a TAB key press and try to 'complete' any existing tokens. The method is handed the current state of the command-line in a string, and it updates the command-line in place.
Parameters
line is current command-line and will hold the final completion
cursor is the current position of the cursor
Returns
the (possibly new) position of the cursor, after completion
References IfaceStatus::comlist, IfaceStatus::expandCom(), IfaceStatus::optr, and IfaceStatus::wordsToString().
Referenced by readLine().
popScript()
void IfaceTerm::popScript (void) virtual
Return to processing the parent stream.
The current input stream, as established by a script, is popped from the stack, along with its command prompt, and processing continues with the previous stream.
Reimplemented from IfaceStatus.
References inputstack, IfaceStatus::popScript(), and sptr.
pushScript()
void IfaceTerm::pushScript (istream * iptr, const string & newprompt) virtual
Provide a new input stream to execute, with an associated command prompt.
The new stream is added to a stack and becomes the primary source for parsing new commands. Once commands from the stream are exhausted, parsing will resume in the previous stream.
Parameters
iptr is the new input stream
newprompt is the command line prompt to associate with the new stream
Reimplemented from IfaceStatus.
References inputstack, IfaceStatus::pushScript(), and sptr.
readLine()
void IfaceTerm::readLine (string & line) private virtual
Read the next command line.
Parameters
line is filled in with the next command to execute
Implements IfaceStatus.
References doCompletion(), IfaceStatus::getHistory(), IfaceStatus::optr, and sptr.
The documentation for this class was generated from the following files:
ifaceterm.hh
ifaceterm.cc