decompiler: StringManagerUnicode Class Reference
StringManagerUnicode Class Reference
An implementation of StringManager that understands terminated unicode strings.
#include <stringmanage.hh>
Public Member Functions
StringManagerUnicode (Architecture *g, int4 max)
Constructor.
virtual const vector< uint1 > & getStringData (const Address &addr, Datatype *charType, bool &isTrunc)
Retrieve string data at the given address as a UTF8 byte array.
bool writeUnicode (ostream &s, uint1 *buffer, int4 size, int4 charsize)
Translate/copy unicode to UTF8.
Public Member Functions inherited from StringManager
StringManager (int4 max)
Constructor.
virtual ~StringManager (void)
Destructor.
bool isString (const Address &addr, Datatype *charType)
void saveXml (ostream &s) const
Save cached strings to a stream as XML.
void restoreXml (const Element *el, const AddrSpaceManager *m)
Restore string cache from XML.
Private Member Functions
int4 checkCharacters (const uint1 *buf, int4 size, int4 charsize) const
Make sure buffer has valid bounded set of unicode.
Private Attributes
Architecture * glb
Underlying architecture.
uint1 * testBuffer
Temporary buffer for pulling in loadimage bytes.
Additional Inherited Members
Static Public Member Functions inherited from StringManager
static bool hasCharTerminator (const uint1 *buffer, int4 size, int4 charsize)
Check for a unicode string terminator.
static int4 readUtf16 (const uint1 *buf, bool bigend)
Read a UTF16 code point from a byte array.
static void writeUtf8 (ostream &s, int4 codepoint)
Write unicode character to stream in UTF8 encoding.
static int4 getCodepoint (const uint1 *buf, int4 charsize, bool bigend, int4 &skip)
Extract next unicode codepoint.
Protected Attributes inherited from StringManager
map< Address, StringData > stringMap
Map from address to string data.
int4 maximumChars
Maximum characters in a string before truncating.
Detailed Description
An implementation of StringManager that understands terminated unicode strings.
This class understands UTF8, UTF16, and UTF32 encodings. It reports a string if its sees a valid encoding that is null terminated.
Constructor & Destructor Documentation
StringManagerUnicode()
StringManagerUnicode::StringManagerUnicode (Architecture * g, int4 max)
Constructor.
Parameters
g is the underlying architecture (and loadimage)
max is the maximum number of bytes to allow in a decoded string
References glb, and testBuffer.
Member Function Documentation
checkCharacters()
int4 StringManagerUnicode::checkCharacters (const uint1 * buf, int4 size, int4 charsize) const private
Make sure buffer has valid bounded set of unicode.
Check that the given buffer contains valid unicode. If the string is encoded in UTF8 or ASCII, we get (on average) a bit of check per character. For UTF16, the surrogate reserved area gives at least some check.
Parameters
buf is the byte array to check
size is the size of the buffer in bytes
charsize is the UTF encoding (1=UTF8, 2=UTF16, 4=UTF32)
Returns
the number of characters or -1 if there is an invalid encoding
References StringManager::getCodepoint(), glb, Translate::isBigEndian(), and Architecture::translate.
Referenced by getStringData().
getStringData()
const vector< uint1 > & StringManagerUnicode::getStringData (const Address & addr, Datatype * charType, bool & isTrunc) virtual
Retrieve string data at the given address as a UTF8 byte array.
If the address does not represent string data, a zero length vector is returned. Otherwise, the string data is fetched, converted to a UTF8 encoding, cached and returned.
Parameters
addr is the given address
charType is a character data-type indicating the encoding
isTrunc passes back whether the string is truncated
Returns
the byte array of UTF8 data
Implements StringManager.
References StringManager::StringData::byteData, checkCharacters(), glb, StringManager::hasCharTerminator(), StringManager::StringData::isTruncated, Architecture::loader, LoadImage::loadFill(), StringManager::maximumChars, StringManager::stringMap, testBuffer, and writeUnicode().
writeUnicode()
bool StringManagerUnicode::writeUnicode (ostream & s, uint1 * buffer, int4 size, int4 charsize)
Translate/copy unicode to UTF8.
Assume the buffer contains a null terminated unicode encoded string. Write the characters out (as UTF8) to the stream.
Parameters
s is the output stream
buffer is the given byte buffer
size is the number of bytes in the buffer
charsize specifies the encoding (1=UTF8 2=UTF16 4=UTF32)
Returns
true if the byte array contains valid unicode
References StringManager::getCodepoint(), glb, Translate::isBigEndian(), StringManager::maximumChars, Architecture::translate, and StringManager::writeUtf8().
Referenced by getStringData().
The documentation for this class was generated from the following files:
stringmanage.hh
stringmanage.cc