decompiler: IfaceDecompCommand Class Reference
IfaceDecompCommand Class Reference
Root class for all decompiler specific commands.
#include <ifacedecomp.hh>
Public Member Functions
virtual void setData (IfaceStatus *root, IfaceData *data)
Associate a specific data object with this command.
virtual string getModule (void) const
Get the formal module name to which this command belongs.
virtual IfaceData * createData (void)
Create a specialized data object for this command (and its module)
virtual void iterationCallback (Funcdata *fd)
Perform the per-function aspect of this command.
void iterateFunctionsAddrOrder (void)
Iterate command over all functions in all scopes.
void iterateFunctionsLeafOrder (void)
Iterate command over all functions in a call-graph traversal.
Public Member Functions inherited from IfaceCommand
virtual void execute (istream &s)=0
void addWord (const string &temp)
Add a token to the command line string associated with this command.
void addWords (const vector< string > &wordlist)
Add words to the associated command line string.
void commandString (string &res) const
Get the complete command line string.
int4 compare (const IfaceCommand &op2) const
Order two commands by their command line strings.
Protected Member Functions
void iterateScopesRecursive (Scope *scope)
Iterate recursively over all functions in given scope.
void iterateFunctionsAddrOrder (Scope *scope)
Iterate over all functions in a given scope.
Protected Attributes
IfaceStatus * status
The console owning this command.
IfaceDecompData * dcp
Data common to decompiler commands.
Detailed Description
Root class for all decompiler specific commands.
Commands share the data object IfaceDecompData and are capable of iterating over all functions in the program/architecture.
Member Function Documentation
createData()
virtual IfaceData* IfaceDecompCommand::createData (void) inline virtual
Create a specialized data object for this command (and its module)
This method is only called once per module
Returns
the newly created data object for the module
Implements IfaceCommand.
getModule()
virtual string IfaceDecompCommand::getModule (void) const inline virtual
Get the formal module name to which this command belongs.
Commands in the same module share data through their registered IfaceData object
Returns
the formal module name
Implements IfaceCommand.
iterateFunctionsAddrOrder() [1/2]
void IfaceDecompCommand::iterateFunctionsAddrOrder (Scope * scope) protected
Iterate over all functions in a given scope.
Runs over every function in the scope calling iterationCallback().
Parameters
scope is the given scope
References Scope::begin(), Scope::end(), FunctionSymbol::getFunction(), and iterationCallback().
iterateFunctionsAddrOrder() [2/2]
void IfaceDecompCommand::iterateFunctionsAddrOrder (void)
Iterate command over all functions in all scopes.
Scopes are traversed depth-first, then within a scope, functions are traversed in address order.
References IfaceDecompData::conf, dcp, iterateScopesRecursive(), and Architecture::symboltab.
Referenced by IfcProduceC::execute(), IfcPrintInputsAll::execute(), IfcDuplicateHash::execute(), IfcCallGraphBuild::execute(), IfcCallGraphBuildQuick::execute(), and iterateScopesRecursive().
iterateFunctionsLeafOrder()
void IfaceDecompCommand::iterateFunctionsLeafOrder (void)
Iterate command over all functions in a call-graph traversal.
Traversal is based on the current CallGraph for the program. Child functions are traversed before their parents.
References IfaceDecompData::cgraph, IfaceDecompData::conf, dcp, and iterationCallback().
Referenced by IfcProducePrototypes::execute(), and IfcCallGraphList::execute().
iterateScopesRecursive()
void IfaceDecompCommand::iterateScopesRecursive (Scope * scope) protected
Iterate recursively over all functions in given scope.
Runs over every function in the scope, or any sub-scope , calling iterationCallback()
Parameters
scope is the given scope
References iterateFunctionsAddrOrder().
Referenced by iterateFunctionsAddrOrder().
iterationCallback()
virtual void IfaceDecompCommand::iterationCallback (Funcdata * fd) inline virtual
Perform the per-function aspect of this command.
Parameters
fd is the particular function to operate on
Reimplemented in IfcCallGraphList, IfcCallGraphBuild, IfcDuplicateHash, IfcPrintInputsAll, IfcProducePrototypes, and IfcProduceC.
Referenced by iterateFunctionsAddrOrder(), and iterateFunctionsLeafOrder().
setData()
virtual void IfaceDecompCommand::setData (IfaceStatus * root, IfaceData * data) inline virtual
Associate a specific data object with this command.
Parameters
root is the interface object this command is registered with
data is the data object the command should use
Implements IfaceCommand.
References dcp, and status.
The documentation for this class was generated from the following files:
ifacedecomp.hh
ifacedecomp.cc