decompiler: ActionSetCasts Class Reference
ActionSetCasts Class Reference
Fill-in CPUI_CAST p-code ops as required by the casting strategy.
#include <coreaction.hh>
Public Member Functions
virtual Action * clone (const ActionGroupList &grouplist) const
Clone the Action.
virtual int4 apply (Funcdata &data)
Make a single attempt to apply this Action.
Public Member Functions inherited from Action
Action (uint4 f, const string &nm, const string &g)
Base constructor for an Action.
virtual void printStatistics (ostream &s) const
Dump statistics to stream.
int4 perform (Funcdata &data)
Perform this action (if necessary)
bool setBreakPoint (uint4 tp, const string &specify)
Set a breakpoint on this action.
virtual void clearBreakPoints (void)
Clear all breakpoints set on this Action.
bool setWarning (bool val, const string &specify)
Set a warning on this action.
bool disableRule (const string &specify)
Disable a specific Rule within this.
bool enableRule (const string &specify)
Enable a specific Rule within this.
virtual void reset (Funcdata &data)
Reset the Action for a new function.
virtual void resetStats (void)
Reset all the counts to zero.
virtual int4 print (ostream &s, int4 num, int4 depth) const
Print a description of this Action to stream.
virtual void printState (ostream &s) const
Print status to stream.
virtual Action * getSubAction (const string &specify)
Retrieve a specific sub-action by name.
virtual Rule * getSubRule (const string &specify)
Retrieve a specific sub-rule by name.
Static Private Member Functions
static void checkPointerIssues (PcodeOp *op, Varnode *vn, Funcdata &data)
Check if the data-type of the given value being used as a pointer makes sense.
static bool testStructOffset0 (Varnode *vn, PcodeOp *op, Datatype *ct, CastStrategy *castStrategy)
Test if the given cast conflict can be resolved by passing to the first structure field.
static bool tryResolutionAdjustment (PcodeOp *op, int4 slot, Funcdata &data)
Try to adjust the input and output Varnodes to eliminate a CAST.
static bool isOpIdentical (Datatype *ct1, Datatype *ct2)
Test if two data-types are operation identical.
static int4 resolveUnion (PcodeOp *op, int4 slot, Funcdata &data)
If the given op reads a pointer to a union, insert the CPUI_PTRSUB that resolves the union.
static int4 castOutput (PcodeOp *op, Funcdata &data, CastStrategy *castStrategy)
Insert cast to output Varnode type after given PcodeOp if it is necessary.
static int4 castInput (PcodeOp *op, int4 slot, Funcdata &data, CastStrategy *castStrategy)
Insert cast to produce the input Varnode to a given PcodeOp if necessary.
static PcodeOp * insertPtrsubZero (PcodeOp *op, int4 slot, Datatype *ct, Funcdata &data)
Insert a PTRSUB with offset 0 that accesses a field of the given data-type.
Additional Inherited Members
Public Types inherited from Action
enum ruleflags {
rule_repeatapply = 4, rule_onceperfunc = 8, rule_oneactperfunc = 16, rule_debug = 32,
rule_warnings_on = 64, rule_warnings_given = 128
}
Boolean behavior properties governing this particular Action.
enum statusflags {
status_start =1, status_breakstarthit =2, status_repeat =4, status_mid =8,
status_end =16, status_actionbreak =32
}
Boolean properties describing the status of an action.
enum breakflags { break_start = 1, tmpbreak_start = 2, break_action = 4, tmpbreak_action = 8 }
Break points associated with an Action.
Protected Member Functions inherited from Action
void issueWarning (Architecture *glb)
Warn that this Action has applied.
bool checkStartBreak (void)
Check start breakpoint.
bool checkActionBreak (void)
Check action breakpoint.
Protected Attributes inherited from Action
int4 lcount
Changes not including last call to apply()
int4 count
Number of changes made by this action so far.
uint4 status
Current status.
uint4 breakpoint
Breakpoint properties.
uint4 flags
Behavior properties.
uint4 count_tests
Number of times apply() has been called.
uint4 count_apply
Number of times apply() made changes.
string name
Name of the action.
string basegroup
Base group this action belongs to.
Detailed Description
Fill-in CPUI_CAST p-code ops as required by the casting strategy.
Setting the casts is complicated by type inference and implied variables. By the time this Action is run, the type inference algorithm has labeled every Varnode with what it thinks the type should be. This casting algorithm tries to get the code to legally match this inference result by adding casts. Following the data flow, it tries the best it can to get each token to match the inferred type. For implied variables, the type is completely determined by the syntax of the output language, so implied casts won't work in this case. For most of these cases, the algorithm just changes the type to that dictated by syntax and gets back on track at the next explicit variable in the flow. It tries to avoid losing pointer types however because any CPUI_PTRADD mst have a pointer input. In this case, it casts to the necessary pointer type immediately.
Member Function Documentation
apply()
int4 ActionSetCasts::apply (Funcdata & data) virtual
Make a single attempt to apply this Action.
This is the main entry point for applying changes to a function that are specific to this Action. The method can inspect whatever it wants to decide if the Action does or does not apply. Changes are indicated by incrementing the count field.
Parameters
data is the function to inspect/modify
Returns
0 for a complete application, -1 for a partial completion (due to breakpoint)
Implements Action.
References AddrSpace::addressToByteInt(), castInput(), castOutput(), checkPointerIssues(), Action::count, CPUI_CAST, CPUI_COPY, CPUI_INT_ADD, CPUI_LOAD, CPUI_PTRADD, CPUI_PTRSUB, CPUI_STORE, PcodeOp::notPrinted(), Funcdata::opRemoveInput(), Funcdata::opSetOpcode(), Funcdata::opUndoPtradd(), resolveUnion(), and TYPE_PTR.
castInput()
int4 ActionSetCasts::castInput (PcodeOp * op, int4 slot, Funcdata & data, CastStrategy * castStrategy) static private
Insert cast to produce the input Varnode to a given PcodeOp if necessary.
This method can also mark a Varnode as an explicit integer constant. Guard against chains of casts.
Parameters
op is the given PcodeOp
slot is the slot of the input Varnode
data is the function being analyzed
castStrategy is used to determine if a cast is necessary
Returns
1 if a change is made, 0 otherwise
References CPUI_CAST, Funcdata::forceFacingType(), Varnode::getHigh(), Funcdata::inheritReadResolution(), insertPtrsubZero(), Varnode::loneDescend(), CastStrategy::markExplicitLongSize(), CastStrategy::markExplicitUnsigned(), Funcdata::newOp(), Funcdata::newUniqueOut(), Funcdata::opInsertBefore(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), testStructOffset0(), tryResolutionAdjustment(), and Varnode::updateType().
Referenced by apply().
castOutput()
int4 ActionSetCasts::castOutput (PcodeOp * op, Funcdata & data, CastStrategy * castStrategy) static private
Insert cast to output Varnode type after given PcodeOp if it is necessary.
Parameters
op is the given PcodeOp
data is the function being analyzed
castStrategy is used to determine if the cast is necessary
Returns
1 if a cast inserted, 0 otherwise
References CastStrategy::castStandard(), CPUI_CAST, CPUI_RETURN, Datatype::findResolve(), Funcdata::forceFacingType(), Varnode::getHigh(), Varnode::getHighTypeDefFacing(), isOpIdentical(), Varnode::loneDescend(), Funcdata::newOp(), Funcdata::newUnique(), Funcdata::opInsertAfter(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), Funcdata::opSetOutput(), Funcdata::setUnionField(), TYPE_ARRAY, TYPE_PTR, TYPE_STRUCT, TYPE_UNION, and Varnode::updateType().
Referenced by apply().
checkPointerIssues()
void ActionSetCasts::checkPointerIssues (PcodeOp * op, Varnode * vn, Funcdata & data) static private
Check if the data-type of the given value being used as a pointer makes sense.
If the data-type is a pointer make sure:
The pointed-to size matches the size of the value being loaded are stored
Any address space attached to the pointer matches the address space of the LOAD/STORE
If any of the conditions are violated, a warning is added to the output.
Parameters
op is the LOAD/STORE acting on a pointer
vn is the given value being used as a pointer
data is the function containing the PcodeOp
References AddrSpace::getContain(), AddrSpace::getName(), Action::name, TYPE_PTR, and Funcdata::warning().
Referenced by apply().
clone()
virtual Action* ActionSetCasts::clone (const ActionGroupList & grouplist) const inline virtual
Clone the Action.
If this Action is a member of one of the groups in the grouplist, this returns a clone of the Action, otherwise NULL is returned.
Parameters
grouplist is the list of groups being cloned
Returns
the cloned Action or NULL
Implements Action.
References ActionGroupList::contains().
insertPtrsubZero()
PcodeOp * ActionSetCasts::insertPtrsubZero (PcodeOp * op, int4 slot, Datatype * ct, Funcdata & data) static private
Insert a PTRSUB with offset 0 that accesses a field of the given data-type.
The data-type can be a structure, in which case the field at offset zero is being accessed. The data-type can reference a union, in which case a specific field is being accessed as indicated by Funcdata::getUnionField. The PTRSUB is inserted right before the given PcodeOp. The indicated input Varnode becomes the PTRSUB input, and the PTRSUB output replaces the Varnode in the PcodeOp.
Parameters
op is the given PcodeOp where the PTRSUB is inserted
slot is the slot corresponding to the indicated Varnode
ct is the data-type produced by the PTRSUB
data is containing Function
Returns
the new PTRSUB op
References CPUI_PTRSUB, Funcdata::newConstant(), Funcdata::newOp(), Funcdata::newUniqueOut(), Funcdata::opInsertBefore(), Funcdata::opSetInput(), Funcdata::opSetOpcode(), and Varnode::updateType().
Referenced by castInput(), and resolveUnion().
isOpIdentical()
bool ActionSetCasts::isOpIdentical (Datatype * ct1, Datatype * ct2) static private
Test if two data-types are operation identical.
If, at a source code level, a variable with data-type ct1 can be legally substituted for another variable with data-type ct2, return true. The substitution must be allowed for all possible operations the variable may be involved in.
Parameters
ct1 is the first data-type
ct2 is the second data-type
References TYPE_PTR.
Referenced by castOutput().
resolveUnion()
int4 ActionSetCasts::resolveUnion (PcodeOp * op, int4 slot, Funcdata & data) static private
If the given op reads a pointer to a union, insert the CPUI_PTRSUB that resolves the union.
Parameters
op is the given PcodeOp
slot is index of the input slot being read
data is the containing function
Returns
1 if a PTRSUB is inserted, 0 otherwise
References Varnode::getHigh(), Funcdata::getUnionField(), insertPtrsubZero(), Funcdata::setUnionField(), and TYPE_PTR.
Referenced by apply().
testStructOffset0()
bool ActionSetCasts::testStructOffset0 (Varnode * vn, PcodeOp * op, Datatype * ct, CastStrategy * castStrategy) static private
Test if the given cast conflict can be resolved by passing to the first structure field.
Test if the given Varnode data-type is a pointer to a structure and if interpreting the data-type as a pointer to the structure's first field will get it to match the desired data-type.
Parameters
vn is the given Varnode
op is the PcodeOp reading the Varnode
ct is the desired data-type
castStrategy is used to determine if the data-types are compatible
Returns
true if a pointer to the first field makes sense
References CastStrategy::castStandard(), Varnode::getHighTypeReadFacing(), TYPE_ARRAY, TYPE_PTR, and TYPE_STRUCT.
Referenced by castInput().
tryResolutionAdjustment()
bool ActionSetCasts::tryResolutionAdjustment (PcodeOp * op, int4 slot, Funcdata & data) static private
Try to adjust the input and output Varnodes to eliminate a CAST.
If input/output data-types are different, it may be due to late merges. For unions, the CAST can sometimes be eliminated by adjusting the data-type resolutions of the Varnodes relative to the PcodeOp
Parameters
op is the PcodeOp reading the input Varnode and writing the output Varnode
slot is the index of the input Varnode
data is the function
Returns
true if an adjustment is made so that a CAST is no longer needed
References Datatype::findCompatibleResolve(), Varnode::getHigh(), and Funcdata::setUnionField().
Referenced by castInput().
The documentation for this class was generated from the following files:
coreaction.hh
coreaction.cc