decompiler: TypeSpacebase Class Reference
TypeSpacebase Class Reference
Special Datatype object used to describe pointers that index into the symbol table.
#include <type.hh>
Public Member Functions
TypeSpacebase (const TypeSpacebase &op)
Construct from another TypeSpacebase.
TypeSpacebase (AddrSpace *id, const Address &frame, Architecture *g)
Construct given an address space, scope, and architecture.
Scope * getMap (void) const
Get the symbol table indexed by this.
Address getAddress (uintb off, int4 sz, const Address &point) const
Construct an Address given an offset.
virtual Datatype * getSubType (uintb off, uintb *newoff) const
Recover component data-type one-level down.
virtual Datatype * nearestArrayedComponentForward (uintb off, uintb *newoff, int4 *elSize) const
virtual Datatype * nearestArrayedComponentBackward (uintb off, uintb *newoff, int4 *elSize) const
virtual int4 compare (const Datatype &op, int4 level) const
Order types for propagation.
virtual int4 compareDependency (const Datatype &op) const
Compare for storage in tree structure.
virtual Datatype * clone (void) const
Clone the data-type.
virtual void saveXml (ostream &s) const
Serialize the data-type to XML.
Public Member Functions inherited from Datatype
Datatype (const Datatype &op)
Construct the base data-type copying low-level properties of another.
Datatype (int4 s, type_metatype m)
Construct the base data-type providing size and meta-type.
bool hasSameVariableBase (const Datatype *ct) const
Are these the same variable length data-type.
uint4 getDisplayFormat (void) const
Get the display format for constants with this data-type.
virtual void printRaw (ostream &s) const
Print a description of the type to stream.
virtual bool isPtrsubMatching (uintb off) const
Is this data-type suitable as input to a CPUI_PTRSUB op.
virtual Datatype * getStripped (void) const
Get a stripped version of this for formal use in formal declarations.
virtual Datatype * resolveInFlow (PcodeOp *op, int4 slot)
Tailor data-type propagation based on Varnode use.
virtual Datatype * findResolve (const PcodeOp *op, int4 slot)
Find a previously resolved sub-type.
virtual int4 findCompatibleResolve (Datatype *ct) const
Find a resolution compatible with the given data-type.
int4 typeOrderBool (const Datatype &op) const
Order this with -op-, treating bool data-type as special.
void saveXmlRef (ostream &s) const
Write an XML reference of this to stream.
Private Member Functions
void restoreXml (const Element *el, TypeFactory &typegrp)
Restore this spacebase data-type from an XML element.
Private Attributes
AddrSpace * spaceid
The address space we are treating as a structure.
Address localframe
Address of function whose symbol table is indexed (or INVALID for "global")
Architecture * glb
Architecture for accessing symbol table.
Friends
class TypeFactory
Additional Inherited Members
Static Public Member Functions inherited from Datatype
static uint4 encodeIntegerFormat (const string &val)
Encode the format attribute from an XML element.
static string decodeIntegerFormat (uint4 val)
Decode the given format value into an XML attribute string.
Protected Types inherited from Datatype
enum {
coretype = 1, chartype = 2, enumtype = 4, poweroftwo = 8,
utf16 = 16, utf32 = 32, opaque_string = 64, variable_length = 128,
has_stripped = 0x100, is_ptrrel = 0x200, type_incomplete = 0x400, needs_resolution = 0x800,
force_format = 0x7000
}
Boolean properties of datatypes.
Protected Member Functions inherited from Datatype
void restoreXmlBasic (const Element *el)
Recover basic data-type properties.
void saveXmlBasic (type_metatype meta, ostream &s) const
Save basic data-type properties.
void saveXmlTypedef (ostream &s) const
Write this as a typedef tag to stream.
void setDisplayFormat (uint4 format)
Set a specific display format.
Static Protected Member Functions inherited from Datatype
static uint8 hashName (const string &nm)
Produce a data-type id by hashing the type name.
static uint8 hashSize (uint8 id, int4 size)
Reversibly hash size into id.
Protected Attributes inherited from Datatype
int4 size
Size (of variable holding a value of this type)
string name
Name of type.
type_metatype metatype
Meta-type - type disregarding size.
sub_metatype submeta
Sub-type of of the meta-type, for comparisons.
uint4 flags
Boolean properties of the type.
uint8 id
A unique id for the type (or 0 if an id is not assigned)
Datatype * typedefImm
The immediate data-type being typedefed by this.
Static Protected Attributes inherited from Datatype
static sub_metatype base2sub [14]
Detailed Description
Special Datatype object used to describe pointers that index into the symbol table.
A TypeSpacebase treats a specific AddrSpace as "structure" that will get indexed in to. This facilitates type propagation from local symbols into the stack space and from global symbols into the RAM space.
Member Function Documentation
compare()
int4 TypeSpacebase::compare (const Datatype & op, int4 level) const virtual
Order types for propagation.
Order this with another data-type, in a way suitable for the type propagation algorithm. Bigger types come earlier. More specific types come earlier.
Parameters
op is the data-type to compare with this
level is maximum level to descend when recursively comparing
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References compareDependency().
compareDependency()
int4 TypeSpacebase::compareDependency (const Datatype & op) const virtual
Compare for storage in tree structure.
Sort data-types for the main TypeFactory container. The sort needs to be based on the data-type structure so that an example data-type, constructed outside the factory, can be used to find the equivalent object inside the factory. This means the comparison should not examine the data-type id. In practice, the comparison only needs to go down one level in the component structure before just comparing component pointers.
Parameters
op is the data-type to compare with this
Returns
negative, 0, positive depending on ordering of types
Reimplemented from Datatype.
References Datatype::compareDependency(), Address::isInvalid(), localframe, and spaceid.
Referenced by compare().
getAddress()
Address TypeSpacebase::getAddress (uintb off, int4 sz, const Address & point) const
Construct an Address given an offset.
Return the Address being referred to by a specific offset relative to a pointer with this Datatype
Parameters
off is the offset relative to the pointer
sz is the size of offset (as a pointer)
point is a "context" reference for the request
Returns
the referred to Address
References glb, Address::isInvalid(), localframe, AddrSpaceManager::resolveConstant(), and spaceid.
Referenced by RulePtrsubCharConstant::applyOp(), Funcdata::linkSymbolReference(), PrintC::opPtrsub(), and ActionInferTypes::propagateSpacebaseRef().
getMap()
Scope * TypeSpacebase::getMap (void) const
Get the symbol table indexed by this.
This data-type can index either a local or the global scope
Returns
the symbol table Scope
References glb, Address::isInvalid(), localframe, Scope::queryFunction(), and Architecture::symboltab.
Referenced by RulePtrsubCharConstant::applyOp(), getSubType(), Funcdata::linkSymbolReference(), and nearestArrayedComponentForward().
getSubType()
Datatype * TypeSpacebase::getSubType (uintb off, uintb * newoff) const virtual
Recover component data-type one-level down.
Given an offset into this data-type, return the component data-type at that offset. Also, pass back a "renormalized" offset suitable for recursize getSubType() calls: i.e. if the original offset hits the exact start of the sub-type, 0 is passed back. If there is no valid component data-type at the offset, return NULL and pass back the original offset
Parameters
off is the offset into this data-type
newoff is a pointer to the passed-back offset
Returns
a pointer to the component data-type or NULL
Reimplemented from Datatype.
References AddrSpace::byteToAddress(), TypeFactory::getBase(), getMap(), Address::getOffset(), AddrSpace::getWordSize(), glb, Scope::queryContainer(), AddrSpaceManager::resolveConstant(), spaceid, TYPE_UNKNOWN, and Architecture::types.
Referenced by nearestArrayedComponentBackward().
nearestArrayedComponentBackward()
Datatype * TypeSpacebase::nearestArrayedComponentBackward (uintb off, uintb * newoff, int4 * elSize) const virtual
Find the first component data-type before the given offset that is (or contains) an array, and pass back the difference between the component's start and the given offset. Return the component data-type or null if no array is found.
Parameters
off is the given offset into this data-type
newoff is used to pass back the offset difference
elSize is used to pass back the array element size
Returns
the component data-type or null
Reimplemented from Datatype.
References getSubType(), Datatype::nearestArrayedComponentBackward(), TYPE_ARRAY, and TYPE_STRUCT.
nearestArrayedComponentForward()
Datatype * TypeSpacebase::nearestArrayedComponentForward (uintb off, uintb * newoff, int4 * elSize) const virtual
Find the first component data-type after the given offset that is (or contains) an array, and pass back the difference between the component's start and the given offset. Return the component data-type or null if no array is found.
Parameters
off is the given offset into this data-type
newoff is used to pass back the offset difference
elSize is used to pass back the array element size
Returns
the component data-type or null
Reimplemented from Datatype.
References AddrSpace::byteToAddress(), AddrSpace::byteToAddressInt(), getMap(), Address::getOffset(), AddrSpace::getWordSize(), glb, Datatype::nearestArrayedComponentForward(), Scope::queryContainer(), AddrSpaceManager::resolveConstant(), spaceid, TYPE_ARRAY, and TYPE_STRUCT.
restoreXml()
void TypeSpacebase::restoreXml (const Element * el, TypeFactory & typegrp) private
Restore this spacebase data-type from an XML element.
Parse the <type> tag.
Parameters
el is the root XML element
typegrp is the factory owning this data-type
Referenced by TypeFactory::restoreXmlTypeNoRef().
saveXml()
void TypeSpacebase::saveXml (ostream & s) const virtual
Serialize the data-type to XML.
Write out a formal description of the data-type as an XML <type> tag. For composite data-types, the description goes down one level, describing the component types only by reference.
Parameters
s is the stream to write to
Reimplemented from Datatype.
References a_v(), AddrSpace::getName(), Datatype::metatype, Datatype::saveXmlBasic(), Datatype::saveXmlTypedef(), spaceid, and Datatype::typedefImm.
The documentation for this class was generated from the following files:
type.hh
type.cc