decompiler: ifacedecomp.hh File Reference
ifacedecomp.hh File Reference
Console interface commands for the decompiler engine.
#include "graph.hh"
#include "grammar.hh"
#include "callgraph.hh"
#include "paramid.hh"
#include "testfunction.hh"
Classes
class IfaceDecompCapability
Interface capability point for all decompiler commands.
class IfaceDecompData
Common data shared by decompiler commands.
class IfaceAssemblyEmit
Disassembly emitter that prints to a console stream.
class IfaceDecompCommand
Root class for all decompiler specific commands.
class IfcSource
Execute a command script : source <filename>
class IfcOption
Adjust a decompiler option: option <optionname> [<param1>] [<param2>] [<param3>]
class IfcParseLine
Parse a line of C syntax: parse line ...
class IfcParseFile
Parse a file with C declarations: parse file <filename>
class IfcAdjustVma
Change the base address of the load image: adjust vma 0xabcd0123
class IfcFuncload
Make a specific function current: load function <functionname>
class IfcAddrrangeLoad
Create a new function at an address: load addr <address> [<funcname>]
class IfcCleararch
Clear the current architecture/program: clear architecture
class IfcReadSymbols
Read in symbols from the load image: read symbols
class IfcMapaddress
Map a new symbol into the program: map address <address> <typedeclaration>
class IfcMaphash
Add a dynamic symbol to the current function: map hash <address> <hash> <typedeclaration>
class IfcMapfunction
Create a new function: map function <address> [<functionname>] [nocode]
class IfcMapexternalref
Create an external ref symbol map externalref <address> <refaddress> [<name>]
class IfcMaplabel
Create a code label: map label <name> <address>
class IfcMapconvert
Create an convert directive: map convert <format> <value> <address> <hash>
class IfcPrintdisasm
Print disassembly of a memory range: disassemble [<address1> <address2>]
class IfcDump
Display bytes in the load image: dump <address+size>
class IfcDumpbinary
Dump a memory to file: binary <address+size> <filename>
class IfcDecompile
Decompile the current function: decompile
class IfcPrintLanguage
Print current output using a specific language: print language <langname>
class IfcPrintCXml
Print the current function with C syntax and XML markup:print C xml
class IfcPrintCFlat
Print current function without control-flow: print C flat
class IfcPrintCStruct
Print the current function using C syntax:print C
class IfcPrintCGlobals
Print declarations for any known global variables: print C globals
class IfcPrintCTypes
Print any known type definitions: print C types
class IfcProduceC
Write decompilation for all functions to a file: produce C <filename>
class IfcProducePrototypes
Determine the prototype model for all functions: produce prototypes
class IfcListaction
List all current actions and rules for the decompiler: list action
class IfcListOverride
Display any overrides for the current function: list override
class IfcListprototypes
List known prototype models: list prototypes
class IfcSetcontextrange
Set a context variable: set context <name> <value> [<startaddress> <endaddress>]
class IfcSettrackedrange
Set the value of a register: set track <name> <value> [<startaddress> <endaddress>]
class IfcBreakstart
Set a break point at the start of an Action: break start <actionname>
class IfcBreakaction
Set a breakpoint when a Rule or Action executes: break action <actionname>
class IfcPrintTree
Print all Varnodes in the current function: print tree varnode
class IfcPrintBlocktree
Print a description of the current functions control-flow: print tree block
class IfcPrintSpaces
Print all address spaces: print spaces
class IfcPrintHigh
Display all Varnodes in a HighVariable: print high <name>
class IfcPrintParamMeasures
Perform parameter-id analysis on the current function: print parammeasures
class IfcRename
Rename a variable: rename <oldname> <newname>
class IfcRetype
Change the data-type of a symbol: retype <symbolname> <typedeclaration>
class IfcRemove
Remove a symbol by name: remove <symbolname>
class IfcPrintVarnode
Print information about a Varnode: print varnode <varnode>
class IfcPrintCover
Print cover info about a HighVariable: print cover high <name>
class IfcVarnodehighCover
Print cover info about a HighVariable: print cover varnodehigh <varnode>
class IfcPrintExtrapop
Print change to stack pointer for called function: print extrapop [<functionname>]
class IfcVarnodeCover
Print cover information about a Varnode: print cover varnode <varnode>
class IfcNameVarnode
Attach a named symbol to a specific Varnode: name varnode <varnode> <name>
class IfcTypeVarnode
Attach a typed symbol to a specific Varnode: type varnode <varnode> <typedeclaration>
class IfcForceFormat
Mark a constant to be printed in a specific format: force varnode <varnode> [hex|dec|oct|bin|char]
class IfcForceDatatypeFormat
Mark constants of a data-type to be printed in a specific format: force datatype <datatype> [hex|dec|oct|bin|char]
class IfcForcegoto
Force a branch to be an unstructured goto: force goto <branchaddr> <targetaddr>
class IfcProtooverride
Override the prototype of a called function: override prototype <address> <declaration>
class IfcJumpOverride
Provide an overriding jump-table for an indirect branch: override jumptable ...
class IfcFlowOverride
Create a control-flow override: override flow <address> branch|call|callreturn|return
class IfcDeadcodedelay
Change when dead code elimination starts: deadcode delay <name> <delay>
class IfcGlobalAdd
Add a memory range as discoverable global variables: global add <address+size>
class IfcGlobalRemove
Remove a memory range from discoverable global variables: global remove <address+size>
class IfcGlobalify
Treat all normal memory as discoverable global variables: global spaces
class IfcGlobalRegisters
Name global registers: global registers
class IfcPrintInputs
Print info about the current function's input Varnodes: print inputs
class IfcPrintInputsAll
Print info about input Varnodes for all functions: print inputs all
class IfcLockPrototype
Lock in the current function's prototype: prototype lock
class IfcUnlockPrototype
Unlock the current function's prototype: prototype unlock
class IfcPrintLocalrange
Print range of locals on the stack: print localrange
class IfcPrintMap
Print info about a scope/namespace: print map <name>
class IfcContinue
Continue decompilation after a break point: continue
class IfcPrintRaw
Print the raw p-code for the current function: print raw
class IfcGraphDataflow
Write a graph representation of data-flow to a file: graph dataflow <filename>
class IfcGraphControlflow
Write a graph representation of control-flow to a file: graph controlflow <filename>
class IfcGraphDom
Write the forward dominance graph to a file: graph dom <filename>
class IfcCommentInstr
Attach a comment to an address: comment <address> comment text...
class IfcDuplicateHash
Check for duplicate hashes in functions: duplicate hash
class IfcCallGraphDump
Write the current call-graph to a file: callgraph dump <filename>
class IfcCallGraphBuild
Build the call-graph for the architecture/program: callgraph build
class IfcCallGraphBuildQuick
Build the call-graph using quick analysis: callgraph build quick
class IfcCallGraphLoad
Load the call-graph from a file: callgraph load <filename>
class IfcCallGraphList
List all functions in leaf order: callgraph list
class IfcComment
A comment within a command script: % A comment in a script
class IfcCallFixup
Add a new call fix-up to the program: fixup call ...
class IfcCallOtherFixup
Add a new callother fix-up to the program: fixup callother ...
class IfcCountPcode
Count p-code in the current function: count pcode
class IfcPrintActionstats
Print transform statistics for the decompiler engine: print actionstats
class IfcResetActionstats
Reset transform statistics for the decompiler engine: reset actionstats
class IfcVolatile
Mark a memory range as volatile: volatile <address+size>
class IfcReadonly
Mark a memory range as read-only: readonly <address+size>
class IfcPointerSetting
Create a pointer with additional settings: pointer setting <name> <basetype> offset <val>
class IfcPreferSplit
Mark a storage location to be split: prefersplit <address+size> <splitsize>
class IfcStructureBlocks
Structure an external control-flow graph: structure blocks <infile> <outfile>
class IfcAnalyzeRange
Run value-set analysis on the current function: analyze range full|partial <varnode>
class IfcLoadTestFile
Load a datatest environment file: load test <filename>
class IfcListTestCommands
List all the script commands in the current test: list test commands
class IfcExecuteTestCommand
Execute a specified range of the test script: `execute test command <#>-<#>
Functions
void execute (IfaceStatus *status, IfaceDecompData *dcp)
Execute one command for the console.
void mainloop (IfaceStatus *status)
Execute commands as they become available.
Detailed Description
Console interface commands for the decompiler engine.
Function Documentation
execute()
void execute (IfaceStatus * status, IfaceDecompData * dcp)
Execute one command for the console.
Execute one command and handle any exceptions. Error messages are printed to the console. For low-level errors, the current function is reset to null
Parameters
status is the console interface
dcp is the shared program data
References IfaceDecompData::abortFunction(), IfaceStatus::evaluateError(), LowlevelError::explain, IfaceError::explain, XmlError::explain, IfaceStatus::optr, and IfaceStatus::runCommand().
Referenced by mainloop().
mainloop()
void mainloop (IfaceStatus * status)
Execute commands as they become available.
Execution loops until either the done field in the console is set or if all streams have ended. This handles popping script states pushed on by the IfcSource command.
Parameters
status is the console interface
References IfaceStatus::done, execute(), IfaceStatus::getData(), IfaceStatus::isStreamFinished(), IfaceStatus::optr, and IfaceStatus::popScript().
Referenced by FunctionTestCollection::runTests().