decompiler: interface.hh File Reference
interface.hh File Reference
Classes and utilities for a generic command-line interface.
#include "capability.hh"
#include <string>
#include <map>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <cstdio>
Classes
struct IfaceError
An exception specific to the command line interface.
struct IfaceParseError
An exception describing a parsing error in a command line.
struct IfaceExecutionError
An exception throw during the execution of a command.
class IfaceData
Data specialized for a particular command module.
class IfaceCommand
A command that can be executed from the command line.
class IfaceCommandDummy
A dummy command used during parsing.
class IfaceCapability
Groups of console commands that are discovered by the loader.
class IfaceStatus
A generic console mode interface and command executor.
class IfaceBaseCommand
A root class for a basic set of commands.
class IfcQuit
Quit command to terminate processing from the given interface.
class IfcHistory
History command to list the most recent successful commands.
class IfcOpenfile
Open file command to redirect bulk output to a specific file stream.
class IfcOpenfileAppend
Open file command directing bulk output to be appended to a specific file.
class IfcClosefile
Close command, closing the current bulk output file.
class IfcEcho
Echo command to echo the current command line to the bulk output stream.
Functions
bool compare_ifacecommand (const IfaceCommand *a, const IfaceCommand *b)
Compare to commands as pointers.
Detailed Description
Classes and utilities for a generic command-line interface.
Function Documentation
compare_ifacecommand()
bool compare_ifacecommand (const IfaceCommand * a, const IfaceCommand * b) inline
Compare to commands as pointers.
Parameters
a is a pointer to the first command
b is a pointer to the second command
Returns
true if the first pointer is ordered before the second
References IfaceCommand::compare().
Referenced by IfaceStatus::restrictCom(), and IfaceStatus::runCommand().