decompiler: type.hh File Reference
type.hh File Reference
Classes for describing and printing data-types.
#include "address.hh"
Classes
class Datatype
The base datatype class for the decompiler.
class TypeField
A field within a structure or union.
struct DatatypeCompare
Compare two Datatype pointers for equivalence of their description.
struct DatatypeNameCompare
Compare two Datatype pointers: first by name, then by id.
class TypeBase
Base class for the fundamental atomic types.
class TypeChar
Base type for character data-types: i.e. char.
class TypeUnicode
The unicode data-type: i.e. wchar.
class TypeVoid
Formal "void" data-type object.
class TypePointer
Datatype object representing a pointer.
class TypeArray
Datatype object representing an array of elements.
class TypeEnum
An enumerated Datatype object: an integer with named values.
class TypeStruct
A composite Datatype object: A structure with component fields.
class TypeUnion
A collection of overlapping Datatype objects: A union of component fields.
class TypePointerRel
class TypeCode
Datatype object representing executable code.
class TypeSpacebase
Special Datatype object used to describe pointers that index into the symbol table.
class TypeFactory
Container class for all Datatype objects in an Architecture.
Typedefs
typedef set< Datatype *, DatatypeCompare > DatatypeSet
A set of data-types sorted by function.
typedef set< Datatype *, DatatypeNameCompare > DatatypeNameSet
A set of data-types sorted by name.
Enumerations
enum type_metatype {
TYPE_VOID = 13, TYPE_SPACEBASE = 12, TYPE_UNKNOWN = 11, TYPE_INT = 10,
TYPE_UINT = 9, TYPE_BOOL = 8, TYPE_CODE = 7, TYPE_FLOAT = 6,
TYPE_PTR = 5, TYPE_PTRREL = 4, TYPE_ARRAY = 3, TYPE_PARTIALSTRUCT = 2,
TYPE_STRUCT = 1, TYPE_UNION = 0
}
enum sub_metatype {
SUB_VOID = 21, SUB_SPACEBASE = 20, SUB_UNKNOWN = 19, SUB_INT_CHAR = 18,
SUB_UINT_CHAR = 17, SUB_INT_PLAIN = 16, SUB_UINT_PLAIN = 15, SUB_INT_ENUM = 14,
SUB_UINT_ENUM = 13, SUB_INT_UNICODE = 12, SUB_UINT_UNICODE = 11, SUB_BOOL = 10,
SUB_CODE = 9, SUB_FLOAT = 8, SUB_PTRREL_UNK = 7, SUB_PTR = 6,
SUB_PTRREL = 5, SUB_PTR_STRUCT = 4, SUB_ARRAY = 3, SUB_PARTIALSTRUCT = 2,
SUB_STRUCT = 1, SUB_UNION = 0
}
Functions
void print_data (ostream &s, uint1 *buffer, int4 size, const Address &baseaddr)
Print a hex dump of a data buffer to stream.
void metatype2string (type_metatype metatype, string &res)
Convert type meta-type to name.
type_metatype string2metatype (const string &metastring)
Convert string to type meta-type.
Detailed Description
Classes for describing and printing data-types.
Enumeration Type Documentation
sub_metatype
enum sub_metatype
Specializations of the core meta-types. Each enumeration is associated with a specific type_metatype. Ordering is important: The lower the number, the more specific the data-type, affecting propagation.
Enumerator
SUB_VOID
Compare as a TYPE_VOID.
SUB_SPACEBASE
Compare as a TYPE_SPACEBASE.
SUB_UNKNOWN
Compare as a TYPE_UNKNOWN.
SUB_INT_CHAR
Signed 1-byte character, sub-type of TYPE_INT.
SUB_UINT_CHAR
Unsigned 1-byte character, sub-type of TYPE_UINT.
SUB_INT_PLAIN
Compare as a plain TYPE_INT.
SUB_UINT_PLAIN
Compare as a plain TYPE_UINT.
SUB_INT_ENUM
Signed enum, sub-type of TYPE_INT.
SUB_UINT_ENUM
Unsigned enum, sub-type of TYPE_UINT.
SUB_INT_UNICODE
Signed wide character, sub-type of TYPE_INT.
SUB_UINT_UNICODE
Unsigned wide character, sub-type of TYPE_UINT.
SUB_BOOL
Compare as TYPE_BOOL.
SUB_CODE
Compare as TYPE_CODE.
SUB_FLOAT
Compare as TYPE_FLOAT.
SUB_PTRREL_UNK
Pointer to unknown field of struct, sub-type of TYPE_PTR.
SUB_PTR
Compare as TYPE_PTR.
SUB_PTRREL
Pointer relative to another data-type, sub-type of TYPE_PTR.
SUB_PTR_STRUCT
Pointer into struct, sub-type of TYPE_PTR.
SUB_ARRAY
Compare as TYPE_ARRAY.
SUB_PARTIALSTRUCT
Compare as TYPE_PARTIALSTRUCT.
SUB_STRUCT
Compare as TYPE_STRUCT.
SUB_UNION
Compare as TYPE_UNION.
type_metatype
enum type_metatype
The core meta-types supported by the decompiler. These are sizeless templates for the elements making up the type algebra.
Enumerator
TYPE_VOID
Standard "void" type, absence of type.
TYPE_SPACEBASE
Placeholder for symbol/type look-up calculations.
TYPE_UNKNOWN
An unknown low-level type. Treated as an unsigned integer.
TYPE_INT
Signed integer. Signed is considered less specific than unsigned in C.
TYPE_UINT
Unsigned integer.
TYPE_BOOL
Boolean.
TYPE_CODE
Data is actual executable code.
TYPE_FLOAT
Floating-point.
TYPE_PTR
Pointer data-type.
TYPE_PTRREL
Pointer relative to another data-type (specialization of TYPE_PTR)
TYPE_ARRAY
Array data-type, made up of a sequence of "element" datatype.
TYPE_PARTIALSTRUCT
Part of a structure, stored separately from the whole.
TYPE_STRUCT
Structure data-type, made up of component datatypes.
TYPE_UNION
An overlapping union of multiple datatypes.
Function Documentation
metatype2string()
void metatype2string (type_metatype metatype, string & res)
Convert type meta-type to name.
Convert a type meta-type into the string name of the meta-type
Parameters
metatype is the encoded type meta-type
res will hold the resulting string
References TYPE_ARRAY, TYPE_BOOL, TYPE_CODE, TYPE_FLOAT, TYPE_INT, TYPE_PARTIALSTRUCT, TYPE_PTR, TYPE_PTRREL, TYPE_SPACEBASE, TYPE_STRUCT, TYPE_UINT, TYPE_UNION, TYPE_UNKNOWN, and TYPE_VOID.
Referenced by Datatype::saveXmlBasic().
print_data()
void print_data (ostream & s, uint1 * buffer, int4 size, const Address & baseaddr)
Print a hex dump of a data buffer to stream.
Display an array of bytes as a hex dump at a given address. Each line displays an address and 16 bytes in hexadecimal
Parameters
s is the stream to write to
buffer is a pointer to the bytes
size is the number of bytes
baseaddr is the address of the first byte in the buffer
References Address::getOffset().
Referenced by IfcDump::execute().
string2metatype()
type_metatype string2metatype (const string & metastring)
Convert string to type meta-type.
Given a string description of a type meta-type. Return the meta-type.
Parameters
metastring is the description of the meta-type
Returns
the encoded type meta-type
References TYPE_ARRAY, TYPE_BOOL, TYPE_CODE, TYPE_FLOAT, TYPE_INT, TYPE_PARTIALSTRUCT, TYPE_PTR, TYPE_PTRREL, TYPE_SPACEBASE, TYPE_STRUCT, TYPE_UINT, TYPE_UNION, TYPE_UNKNOWN, and TYPE_VOID.
Referenced by ParamEntry::restoreXml(), Datatype::restoreXmlBasic(), and TypeFactory::restoreXmlTypeNoRef().